abstract class States {
  static List<String> states = [
    "All states (Nigeria)",
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Cross River",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "FCT Abuja",
    "Gombe",
    "Imo",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Nasarawa",
    "Niger",
    "Ogun",
    "Ondo",
    "Osun",
    "Oyo",
    "Plateau",
    "Rivers",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ];

  static Map<String, List<String>> facilities = {
    "Abia": [
      "Abia General Hospital",
      "Greenfield Medical Center",
      "Sunrise Hospital",
      "Evergreen Medical Center",
      "Springfield Hospital",
      "Hilltop Medical Center",
      "Pristine Medical Center",
      "Grandview Hospital",
      "Blossom Hospital",
      "Hope Medical Center"
    ],
    "Adamawa": [
      "Adamawa Specialist Hospital",
      "Bright Star Medical Center",
      "New Horizons Hospital",
      "Savannah Medical Center",
      "City View Hospital",
      "Oasis Medical Center",
      "Valley Hospital",
      "Golden Gate Medical Center",
      "Emerald Medical Center",
      "Sunset Hospital"
    ],
    "Akwa Ibom": [
      "Akwa Ibom General Hospital",
      "Rainbow Medical Center",
      "Coastal Hospital",
      "Palmview Medical Center",
      "Marina Hospital",
      "Harmony Medical Center",
      "Coral Hospital",
      "Azure Medical Center",
      "Seaside Hospital",
      "Ocean View Hospital"
    ],
    "Anambra": [
      "Anambra Specialist Hospital",
      "Golden City Medical Center",
      "Noble Hospital",
      "Vitality Medical Center",
      "Aureus Hospital",
      "Serenity Medical Center",
      "Everest Hospital",
      "Unity Medical Center",
      "Crescent Hospital",
      "Grace Medical Center"
    ],
    "Bauchi": [
      "Bauchi General Hospital",
      "Highland Medical Center",
      "Silverline Hospital",
      "Mountain View Medical Center",
      "Windsor Hospital",
      "Aspen Medical Center",
      "Majestic Hospital",
      "Peak Medical Center",
      "Cedar Hospital",
      "Elevation Hospital"
    ],
    "Bayelsa": [
      "Bayelsa Specialist Hospital",
      "Emerald City Medical Center",
      "Rainforest Hospital",
      "Palm Grove Medical Center",
      "Lagoon Hospital",
      "Tropical Medical Center",
      "Silverbay Hospital",
      "Jade Medical Center",
      "Paradise Hospital",
      "Waterfront Hospital"
    ],
    "Benue": [
      "Benue General Hospital",
      "Golden Meadow Medical Center",
      "Sunset Hills Hospital",
      "Vineyard Medical Center",
      "Haven Hospital",
      "Lily Hospital",
      "Amber Medical Center",
      "Harvest Medical Center",
      "Valiant Hospital",
      "Meadowlark Hospital"
    ],
    "Borno": [
      "Borno Specialist Hospital",
      "Sahara Medical Center",
      "Desert Oasis Hospital",
      "Sandstorm Medical Center",
      "Serengeti Hospital",
      "Pyramid Medical Center",
      "Cactus Hospital",
      "Savanna Medical Center",
      "Oryx Hospital",
      "Nomad Hospital"
    ],
    "Cross River": [
      "Cross River General Hospital",
      "Jungle Medical Center",
      "Riverfront Hospital",
      "Canopy Medical Center",
      "Rainforest Hospital",
      "Treetop Medical Center",
      "Wildflower Hospital",
      "Raindrop Medical Center",
      "Tropical Grove Hospital",
      "Cascade Hospital"
    ],
    "Delta": [
      "Delta General Hospital",
      "Sunshine Medical Center",
      "Blue Sky Hospital",
      "Harmony Medical Center",
      "Diamond Hospital",
      "Sapphire Medical Center",
      "Starlight Hospital",
      "Celestial Medical Center",
      "Azure Hospital",
      "Lakeside Hospital"
    ],
    "Ebonyi": [
      "Ebonyi Specialist Hospital",
      "Silverstone Medical Center",
      "Crystal Hospital",
      "Serenity Medical Center",
      "Onyx Hospital",
      "Emerald Medical Center",
      "Ivory Hospital",
      "Tranquil Medical Center",
      "Opal Hospital",
      "Pearl Medical Center"
    ],
    "Edo": [
      "Edo General Hospital",
      "Royal Medical Center",
      "Crown Hospital",
      "Palace Medical Center",
      "Imperial Hospital",
      "Majesty Medical Center",
      "Regal Hospital",
      "Sovereign Medical Center",
      "Noble Hospital",
      "Kingdom Hospital"
    ],
    "Ekiti": [
      "Ekiti General Hospital",
      "Sunflower Medical Center",
      "Meadow Hospital",
      "Petal Medical Center",
      "Lily Hospital",
      "Blossom Medical Center",
      "Primrose Hospital",
      "Daisy Medical Center",
      "Tulip Hospital",
      "Orchid Medical Center"
    ],
    "Enugu": [
      "Enugu Specialist Hospital",
      "Golden Gate Medical Center",
      "Sunset Hills Hospital",
      "Evergreen Medical Center",
      "Rainforest Hospital",
      "Valley Medical Center",
      "Mountainview Hospital",
      "Pristine Medical Center",
      "Greenfield Hospital",
      "Skyline Medical Center"
    ],
    "FCT Abuja": [
      "Abuja National Hospital",
      "Capital Medical Center",
      "City View Hospital",
      "Unity Medical Center",
      "Federal Medical Center",
      "Grandview Hospital",
      "Noble Medical Center",
      "Prestige Hospital",
      "Metropolis Medical Center",
      "Central Hospital"
    ],
    "Gombe": [
      "Gombe General Hospital",
      "Sunrise Medical Center",
      "Horizon Hospital",
      "Mountain Peak Medical Center",
      "Highland Hospital",
      "Pristine Medical Center",
      "Crescent Medical Center",
      "Valley View Hospital",
      "Cascade Hospital",
      "Zenith Medical Center"
    ],
    "Imo": [
      "Imo General Hospital",
      "Sunshine Medical Center",
      "Rainbow Hospital",
      "Evergreen Medical Center",
      "Springfield Hospital",
      "Hilltop Medical Center",
      "Blossom Hospital",
      "Pristine Medical Center",
      "Grandview Hospital",
      "Harmony Medical Center"
    ],
    "Jigawa": [
      "Jigawa Specialist Hospital",
      "Bright Star Medical Center",
      "New Horizons Hospital",
      "Savannah Medical Center",
      "City View Hospital",
      "Oasis Medical Center",
      "Valley Hospital",
      "Golden Gate Medical Center",
      "Emerald Medical Center",
      "Sunset Hospital"
    ],
    "Kaduna": [
      "Kaduna General Hospital",
      "Golden City Medical Center",
      "Sunset Hills Hospital",
      "Vitality Medical Center",
      "Aureus Hospital",
      "Serenity Medical Center",
      "Everest Hospital",
      "Unity Medical Center",
      "Crescent Hospital",
      "Grace Medical Center"
    ],
    "Kano": [
      "Kano Specialist Hospital",
      "Silverline Medical Center",
      "Golden Meadow Medical Center",
      "Sunset Hills Hospital",
      "Vineyard Medical Center",
      "Haven Hospital",
      "Lily Hospital",
      "Amber Medical Center",
      "Harvest Medical Center",
      "Valiant Hospital"
    ],
    "Katsina": [
      "Katsina General Hospital",
      "Golden Meadow Medical Center",
      "Sunset Hills Hospital",
      "Vineyard Medical Center",
      "Haven Hospital",
      "Lily Hospital",
      "Amber Medical Center",
      "Harvest Medical Center",
      "Valiant Hospital",
      "Meadowlark Hospital"
    ],
    "Kebbi": [
      "Kebbi General Hospital",
      "Sahara Medical Center",
      "Desert Oasis Hospital",
      "Sandstorm Medical Center",
      "Serengeti Hospital",
      "Pyramid Medical Center",
      "Cactus Hospital",
      "Savanna Medical Center",
      "Oryx Hospital",
      "Nomad Hospital"
    ],
    "Kogi": [
      "Kogi General Hospital",
      "Jungle Medical Center",
      "Riverfront Hospital",
      "Canopy Medical Center",
      "Rainforest Hospital",
      "Treetop Medical Center",
      "Wildflower Hospital",
      "Raindrop Medical Center",
      "Tropical Grove Hospital",
      "Cascade Hospital"
    ],
    "Kwara": [
      "Kwara General Hospital",
      "Sunshine Medical Center",
      "Blue Sky Hospital",
      "Harmony Medical Center",
      "Diamond Hospital",
      "Sapphire Medical Center",
      "Starlight Hospital",
      "Celestial Medical Center",
      "Azure Hospital",
      "Lakeside Hospital"
    ],
    "Lagos": [
      "Lagos General Hospital",
      "Silverstone Medical Center",
      "Crystal Hospital",
      "Serenity Medical Center",
      "Onyx Hospital",
      "Emerald Medical Center",
      "Ivory Hospital",
      "Tranquil Medical Center",
      "Opal Hospital",
      "Pearl Medical Center"
    ],
    "Nasarawa": [
      "Nasarawa Specialist Hospital",
      "Royal Medical Center",
      "Crown Hospital",
      "Palace Medical Center",
      "Imperial Hospital",
      "Majesty Medical Center",
      "Regal Hospital",
      "Sovereign Medical Center",
      "Noble Hospital",
      "Kingdom Hospital"
    ],
    "Niger": [
      "Niger General Hospital",
      "Sunflower Medical Center",
      "Meadow Hospital",
      "Petal Medical Center",
      "Lily Hospital",
      "Blossom Medical Center",
      "Primrose Hospital",
      "Daisy Medical Center",
      "Tulip Hospital",
      "Orchid Medical Center"
    ],
    "Ogun": [
      "Ogun General Hospital",
      "Golden Gate Medical Center",
      "Sunset Hills Hospital",
      "Evergreen Medical Center",
      "Rainforest Hospital",
      "Valley Medical Center",
      "Mountainview Hospital",
      "Pristine Medical Center",
      "Greenfield Hospital",
      "Skyline Medical Center"
    ],
    "Ondo": [
      "Ondo General Hospital",
      "Abuja National Hospital",
      "Capital Medical Center",
      "City View Hospital",
      "Unity Medical Center",
      "Federal Medical Center",
      "Grandview Hospital",
      "Noble Medical Center",
      "Prestige Hospital",
      "Metropolis Medical Center"
    ],
    "Osun": [
      "Osun General Hospital",
      "Sunrise Medical Center",
      "Horizon Hospital",
      "Mountain Peak Medical Center",
      "Highland Hospital",
      "Pristine Medical Center",
      "Crescent Medical Center",
      "Valley View Hospital",
      "Cascade Hospital",
      "Zenith Medical Center"
    ],
    "Oyo": [
      "Oyo General Hospital",
      "Sunshine Medical Center",
      "Rainbow Hospital",
      "Evergreen Medical Center",
      "Springfield Hospital",
      "Hilltop Medical Center",
      "Blossom Hospital",
      "Pristine Medical Center",
      "Grandview Hospital",
      "Harmony Medical Center"
    ],
    "Plateau": [
      "Plateau Specialist Hospital",
      "Bright Star Medical Center",
      "New Horizons Hospital",
      "Savannah Medical Center",
      "City View Hospital",
      "Oasis Medical Center",
      "Valley Hospital",
      "Golden Gate Medical Center",
      "Emerald Medical Center",
      "Sunset Hospital"
    ],
    "Rivers": [
      "Rivers General Hospital",
      "Golden City Medical Center",
      "Sunset Hills Hospital",
      "Vitality Medical Center",
      "Aureus Hospital",
      "Serenity Medical Center",
      "Everest Hospital",
      "Unity Medical Center",
      "Crescent Hospital",
      "Grace Medical Center"
    ],
    "Sokoto": [
      "Sokoto General Hospital",
      "Silverline Medical Center",
      "Golden Meadow Medical Center",
      "Sunset Hills Hospital",
      "Vineyard Medical Center",
      "Haven Hospital",
      "Lily Hospital",
      "Amber Medical Center",
      "Harvest Medical Center",
      "Valiant Hospital"
    ],
    "Taraba": [
      "Taraba Specialist Hospital",
      "Silverstone Medical Center",
      "Crystal Hospital",
      "Serenity Medical Center",
      "Onyx Hospital",
      "Emerald Medical Center",
      "Ivory Hospital",
      "Tranquil Medical Center",
      "Opal Hospital",
      "Pearl Medical Center"
    ],
    "Yobe": [
      "Yobe General Hospital",
      "Royal Medical Center",
      "Crown Hospital",
      "Palace Medical Center",
      "Imperial Hospital",
      "Majesty Medical Center",
      "Regal Hospital",
      "Sovereign Medical Center",
      "Noble Hospital",
      "Kingdom Hospital"
    ],
    "Zamfara": [
      "Zamfara General Hospital",
      "Sunflower Medical Center",
      "Meadow Hospital",
      "Petal Medical Center",
      "Lily Hospital",
      "Blossom Medical Center",
      "Primrose Hospital",
      "Daisy Medical Center",
      "Tulip Hospital",
      "Orchid Medical Center"
    ]
  };
}
