// This file is auto-generated. Do not edit manually.

final Map<String, List<String>> cmaps = {
  'AF': [
    'Badakhshān',
    'Baghlān',
    'Balkh',
    'Bādghīs',
    'Bāmyān',
    'Dāykundī',
    'Farāh',
    'Fāryāb',
    'Ghaznī',
    'Ghōr',
    'Helmand',
    'Herāt',
    'Jowzjān',
    'Kandahār',
    'Khōst',
    'Kunar',
    'Kunduz',
    'Kābul',
    'Kāpīsā',
    'Laghmān',
    'Lōgar',
    'Nangarhār',
    'Nīmrōz',
    'Nūristān',
    'Paktiyā',
    'Paktīkā',
    'Panjshayr',
    'Parwān',
    'Samangān',
    'Sar-e Pul',
    'Takhār',
    'Uruzgān',
    'Wardak',
    'Zābul'
  ],
  'AL': [
    'Berat',
    'Dibër',
    'Durrës',
    'Elbasan',
    'Fier',
    'Gjirokastër',
    'Korçë',
    'Kukës',
    'Lezhë',
    'Shkodër',
    'Tiranë',
    'Vlorë'
  ],
  'DZ': [
    'Adrar',
    'Alger',
    'Annaba',
    'Aïn Defla',
    'Aïn Témouchent',
    'Batna',
    'Biskra',
    'Blida',
    'Bordj Bou Arréridj',
    'Bouira',
    'Boumerdès',
    'Béchar',
    'Béjaïa',
    'Chlef',
    'Constantine',
    'Djelfa',
    'El Bayadh',
    'El Oued',
    'El Tarf',
    'Ghardaïa',
    'Guelma',
    'Illizi',
    'Jijel',
    'Khenchela',
    'Laghouat',
    'Mascara',
    'Mila',
    'Mostaganem',
    'Msila',
    'Médéa',
    'Naama',
    'Oran',
    'Ouargla',
    'Oum el Bouaghi',
    'Relizane',
    'Saïda',
    'Sidi Bel Abbès',
    'Skikda',
    'Souk Ahras',
    'Sétif',
    'Tamanghasset',
    'Tiaret',
    'Tindouf',
    'Tipaza',
    'Tissemsilt',
    'Tizi Ouzou',
    'Tlemcen',
    'Tébessa'
  ],
  'AD': [
    'Andorra la Vella',
    'Canillo',
    'Encamp',
    'Escaldes-Engordany',
    'La Massana',
    'Ordino',
    'Sant Julià de Lòria'
  ],
  'AO': [
    'Bengo',
    'Benguela',
    'Bié',
    'Cabinda',
    'Cunene',
    'Huambo',
    'Huíla',
    'Kuando Kubango',
    'Kwanza Norte',
    'Kwanza Sul',
    'Luanda',
    'Lunda Norte',
    'Lunda Sul',
    'Malange',
    'Moxico',
    'Namibe',
    'Uíge',
    'Zaire'
  ],
  'AG': [
    'Barbuda',
    'Redonda',
    'Saint George',
    'Saint John',
    'Saint Mary',
    'Saint Paul',
    'Saint Peter',
    'Saint Philip'
  ],
  'AR': [
    'Buenos Aires',
    'Catamarca',
    'Chaco',
    'Chubut',
    'Ciudad Autónoma de Buenos Aires',
    'Corrientes',
    'Córdoba',
    'Entre Ríos',
    'Formosa',
    'Jujuy',
    'La Pampa',
    'La Rioja',
    'Mendoza',
    'Misiones',
    'Neuquén',
    'Río Negro',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Cruz',
    'Santa Fe',
    'Santiago del Estero',
    'Tierra del Fuego',
    'Tucumán'
  ],
  'AM': [
    'Aragac̣otn',
    'Ararat',
    'Armavir',
    'Erevan',
    'Geġark\'unik\'',
    'Kotayk\'',
    'Loṙi',
    'Syunik\'',
    'Tavuš',
    'Vayoć Jor',
    'Širak'
  ],
  'AU': [
    'Australian Capital Territory',
    'New South Wales',
    'Northern Territory',
    'Queensland',
    'South Australia',
    'Tasmania',
    'Victoria',
    'Western Australia'
  ],
  'AT': [
    'Burgenland',
    'Kärnten',
    'Niederösterreich',
    'Oberösterreich',
    'Salzburg',
    'Steiermark',
    'Tirol',
    'Vorarlberg',
    'Wien'
  ],
  'AZ': ['Naxçıvan'],
  'BS': [
    'Acklins',
    'Berry Islands',
    'Bimini',
    'Black Point',
    'Cat Island',
    'Central Abaco',
    'Central Andros',
    'Central Eleuthera',
    'City of Freeport',
    'Crooked Island and Long Cay',
    'East Grand Bahama',
    'Exuma',
    'Grand Cay',
    'Harbour Island',
    'Hope Town',
    'Inagua',
    'Long Island',
    'Mangrove Cay',
    'Mayaguana',
    'Moores Island',
    'North Abaco',
    'North Andros',
    'North Eleuthera',
    'Ragged Island',
    'Rum Cay',
    'San Salvador',
    'South Abaco',
    'South Andros',
    'South Eleuthera',
    'Spanish Wells',
    'West Grand Bahama'
  ],
  'BH': [
    'Al Janūbīyah',
    'Al Manāmah',
    'Al Muḩarraq',
    'Al Wusţá',
    'Ash Shamālīyah'
  ],
  'BD': [
    'Barisal',
    'Chittagong',
    'Dhaka',
    'Khulna',
    'Rajshahi',
    'Rangpur',
    'Sylhet'
  ],
  'BB': [
    'Christ Church',
    'Saint Andrew',
    'Saint George',
    'Saint James',
    'Saint John',
    'Saint Joseph',
    'Saint Lucy',
    'Saint Michael',
    'Saint Peter',
    'Saint Philip',
    'Saint Thomas'
  ],
  'BY': [
    'Brestskaya voblasts\'',
    'Homyel\'skaya voblasts\'',
    'Horad Minsk',
    'Hrodzenskaya voblasts\'',
    'Mahilyowskaya voblasts\'',
    'Minskaya voblasts\'',
    'Vitsyebskaya voblasts\''
  ],
  'BE': ['Brussels Hoofdstedelijk Gewest', 'Région Wallonne', 'Vlaams Gewest'],
  'BZ': ['Belize', 'Cayo', 'Corozal', 'Orange Walk', 'Stann Creek', 'Toledo'],
  'BJ': [
    'Alibori',
    'Atakora',
    'Atlantique',
    'Borgou',
    'Collines',
    'Donga',
    'Kouffo',
    'Littoral',
    'Mono',
    'Ouémé',
    'Plateau',
    'Zou'
  ],
  'BT': [
    'Bumthang',
    'Chhukha',
    'Dagana',
    'Gasa',
    'Ha',
    'Lhuentse',
    'Monggar',
    'Paro',
    'Pemagatshel',
    'Punakha',
    'Samdrup Jongkha',
    'Samtse',
    'Sarpang',
    'Thimphu',
    'Trashi Yangtse',
    'Trashigang',
    'Trongsa',
    'Tsirang',
    'Wangdue Phodrang',
    'Zhemgang'
  ],
  'BO': [
    'Chuquisaca',
    'Cochabamba',
    'El Beni',
    'La Paz',
    'Oruro',
    'Pando',
    'Potosí',
    'Santa Cruz',
    'Tarija'
  ],
  'BA': [
    'Brčko distrikt',
    'Federacija Bosna i Hercegovina',
    'Republika Srpska'
  ],
  'BW': [
    'Central',
    'Chobe',
    'Francistown',
    'Gaborone',
    'Ghanzi',
    'Jwaneng',
    'Kgalagadi',
    'Kgatleng',
    'Kweneng',
    'Lobatse',
    'North-East',
    'North-West',
    'Selibe Phikwe',
    'South-East',
    'Southern',
    'Sowa Town'
  ],
  'BR': [
    'Acre',
    'Alagoas',
    'Amapá',
    'Amazonas',
    'Bahia',
    'Ceará',
    'Distrito Federal',
    'Espírito Santo',
    'Goiás',
    'Maranhão',
    'Mato Grosso',
    'Mato Grosso do Sul',
    'Minas Gerais',
    'Paraná',
    'Paraíba',
    'Pará',
    'Pernambuco',
    'Piauí',
    'Rio Grande do Norte',
    'Rio Grande do Sul',
    'Rio de Janeiro',
    'Rondônia',
    'Roraima',
    'Santa Catarina',
    'Sergipe',
    'São Paulo',
    'Tocantins'
  ],
  'UM': [
    'Baker Island',
    'Howland Island',
    'Jarvis Island',
    'Johnston Atoll',
    'Kingman Reef',
    'Midway Islands',
    'Navassa Island',
    'Palmyra Atoll',
    'Wake Island'
  ],
  'BN': ['Belait', 'Brunei-Muara', 'Temburong', 'Tutong'],
  'BG': [
    'Blagoevgrad',
    'Burgas',
    'Dobrich',
    'Gabrovo',
    'Haskovo',
    'Kardzhali',
    'Kyustendil',
    'Lovech',
    'Montana',
    'Pazardzhik',
    'Pernik',
    'Pleven',
    'Plovdiv',
    'Razgrad',
    'Ruse',
    'Shumen',
    'Silistra',
    'Sliven',
    'Smolyan',
    'Sofia',
    'Sofia-Grad',
    'Stara Zagora',
    'Targovishte',
    'Varna',
    'Veliko Tarnovo',
    'Vidin',
    'Vratsa',
    'Yambol'
  ],
  'BF': [
    'Boucle du Mouhoun',
    'Cascades',
    'Centre',
    'Centre-Est',
    'Centre-Nord',
    'Centre-Ouest',
    'Centre-Sud',
    'Est',
    'Hauts-Bassins',
    'Nord',
    'Plateau-Central',
    'Sahel',
    'Sud-Ouest'
  ],
  'BI': [
    'Bubanza',
    'Bujumbura Mairie',
    'Bujumbura Rural',
    'Bururi',
    'Cankuzo',
    'Cibitoke',
    'Gitega',
    'Karuzi',
    'Kayanza',
    'Kirundo',
    'Makamba',
    'Muramvya',
    'Muyinga',
    'Mwaro',
    'Ngozi',
    'Rutana',
    'Ruyigi'
  ],
  'KH': [
    'Baat Dambang',
    'Banteay Mean Chey',
    'Kampong Chaam',
    'Kampong Chhnang',
    'Kampong Spueu',
    'Kampong Thum',
    'Kampot',
    'Kandaal',
    'Kaoh Kong',
    'Kracheh',
    'Krong Kaeb',
    'Krong Pailin',
    'Krong Preah Sihanouk',
    'Mondol Kiri',
    'Otdar Mean Chey',
    'Phnom Penh',
    'Pousaat',
    'Preah Vihear',
    'Prey Veaeng',
    'Rotanak Kiri',
    'Siem Reab',
    'Stueng Traeng',
    'Svaay Rieng',
    'Taakaev'
  ],
  'CM': [
    'Adamaoua',
    'Centre',
    'East',
    'Far North',
    'Littoral',
    'North',
    'North-West',
    'South',
    'South-West',
    'West'
  ],
  'CA': [
    'Alberta',
    'British Columbia',
    'Manitoba',
    'New Brunswick',
    'Newfoundland and Labrador',
    'Nova Scotia',
    'Ontario',
    'Prince Edward Island',
    'Quebec',
    'Saskatchewan',
    'Northwest Territories',
    'Nunavut',
    'Yukon'
  ],
  'CV': ['Ilhas de Barlavento', 'Ilhas de Sotavento'],
  'CF': [
    'Bamingui-Bangoran',
    'Bangui',
    'Basse-Kotto',
    'Gribingui',
    'Haut-Mbomou',
    'Haute-Kotto',
    'Haute-Sangha / Mambéré-Kadéï',
    'Kémo-Gribingui',
    'Lobaye',
    'Mbomou',
    'Nana-Mambéré',
    'Ombella-Mpoko',
    'Ouaka',
    'Ouham',
    'Ouham-Pendé',
    'Sangha',
    'Vakaga'
  ],
  'TD': [
    'Al Baṭḩah',
    'Al Buḩayrah',
    'Baḩr al Ghazāl',
    'Būrkū',
    'Innīdī',
    'Kānim',
    'Lūqūn al Gharbī',
    'Lūqūn ash Sharqī',
    'Madīnat Injamīnā',
    'Māndūl',
    'Māyū Kībbī al Gharbī',
    'Māyū Kībbī ash Sharqī',
    'Qīrā',
    'Salāmāt',
    'Shārī Bāqirmī',
    'Shārī al Awsaṭ',
    'Sīlā',
    'Tibastī',
    'Tānjilī',
    'Waddāy',
    'Wādī Fīrā',
    'Ḥajjar Lamīs'
  ],
  'CL': [
    'Aisén del General Carlos Ibañez del Campo',
    'Antofagasta',
    'Araucanía',
    'Arica y Parinacota',
    'Atacama',
    'Bío-Bío',
    'Coquimbo',
    'Libertador General Bernardo O\'Higgins',
    'Los Lagos',
    'Los Ríos',
    'Magallanes',
    'Maule',
    'Región Metropolitana de Santiago',
    'Tarapacá',
    'Valparaíso'
  ],
  'CN': [
    'Guangxi',
    'Nei Mongol',
    'Ningxia',
    'Xinjiang',
    'Xizang',
    'Beijing',
    'Chongqing',
    'Shanghai',
    'Tianjin',
    'Anhui',
    'Fujian',
    'Gansu',
    'Guangdong',
    'Guizhou',
    'Hainan',
    'Hebei',
    'Heilongjiang',
    'Henan',
    'Hubei',
    'Hunan',
    'Jiangsu',
    'Jiangxi',
    'Jilin',
    'Liaoning',
    'Qinghai',
    'Shaanxi',
    'Shandong',
    'Shanxi',
    'Sichuan',
    'Taiwan',
    'Yunnan',
    'Zhejiang',
    'Hong Kong',
    'Macao',
    'Hong Kong Island',
    'Kowloon',
    'New Territories'
  ],
  'CO': [
    'Amazonas',
    'Antioquia',
    'Arauca',
    'Atlántico',
    'Bolívar',
    'Boyacá',
    'Caldas',
    'Caquetá',
    'Casanare',
    'Cauca',
    'Cesar',
    'Chocó',
    'Cundinamarca',
    'Córdoba',
    'Distrito Capital de Bogotá',
    'Guainía',
    'Guaviare',
    'Huila',
    'La Guajira',
    'Magdalena',
    'Meta',
    'Nariño',
    'Norte de Santander',
    'Putumayo',
    'Quindío',
    'Risaralda',
    'San Andrés, Providencia y Santa Catalina',
    'Santander',
    'Sucre',
    'Tolima',
    'Valle del Cauca',
    'Vaupés',
    'Vichada'
  ],
  'KM': ['Anjouan', 'Grande Comore', 'Mohéli'],
  'CG': [
    'Bouenza',
    'Brazzaville',
    'Cuvette',
    'Cuvette-Ouest',
    'Kouilou',
    'Likouala',
    'Lékoumou',
    'Niari',
    'Plateaux',
    'Pointe-Noire',
    'Pool',
    'Sangha'
  ],
  'CD': [
    'Bandundu',
    'Bas-Congo',
    'Kasai-Occidental',
    'Kasai-Oriental',
    'Katanga',
    'Kinshasa',
    'Maniema',
    'Nord-Kivu',
    'Orientale',
    'Sud-Kivu',
    'Équateur'
  ],
  'CR': [
    'Alajuela',
    'Cartago',
    'Guanacaste',
    'Heredia',
    'Limón',
    'Puntarenas',
    'San José'
  ],
  'HR': [
    'Bjelovarsko-bilogorska županija',
    'Brodsko-posavska županija',
    'Dubrovačko-neretvanska županija',
    'Grad Zagreb',
    'Istarska županija',
    'Karlovačka županija',
    'Koprivničko-križevačka županija',
    'Krapinsko-zagorska županija',
    'Ličko-senjska županija',
    'Međimurska županija',
    'Osječko-baranjska županija',
    'Požeško-slavonska županija',
    'Primorsko-goranska županija',
    'Sisačko-moslavačka županija',
    'Splitsko-dalmatinska županija',
    'Varaždinska županija',
    'Virovitičko-podravska županija',
    'Vukovarsko-srijemska županija',
    'Zadarska županija',
    'Zagrebačka županija',
    'Šibensko-kninska županija'
  ],
  'CU': [
    'Artemisa',
    'Camagüey',
    'Ciego de Ávila',
    'Cienfuegos',
    'Granma',
    'Guantánamo',
    'Holguín',
    'Isla de la Juventud',
    'La Habana',
    'Las Tunas',
    'Matanzas',
    'Mayabeque',
    'Pinar del Río',
    'Sancti Spíritus',
    'Santiago de Cuba',
    'Villa Clara'
  ],
  'CY': ['Ammochostos', 'Keryneia', 'Larnaka', 'Lefkosia', 'Lemesos', 'Pafos'],
  'CZ': [
    'Jihomoravský kraj',
    'Jihočeský kraj',
    'Karlovarský kraj',
    'Královéhradecký kraj',
    'Liberecký kraj',
    'Moravskoslezský kraj',
    'Olomoucký kraj',
    'Pardubický kraj',
    'Plzeňský kraj',
    'Praha, hlavní město',
    'Středočeský kraj',
    'Vysočina',
    'Zlínský kraj',
    'Ústecký kraj'
  ],
  'DK': ['Hovedstaden', 'Midtjylland', 'Nordjylland', 'Sjælland', 'Syddanmark'],
  'DJ': ['Ali Sabieh', 'Arta', 'Dikhil', 'Djibouti', 'Obock', 'Tadjourah'],
  'DM': [
    'Saint Andrew',
    'Saint David',
    'Saint George',
    'Saint John',
    'Saint Joseph',
    'Saint Luke',
    'Saint Mark',
    'Saint Patrick',
    'Saint Paul',
    'Saint Peter'
  ],
  'DO': [
    'Cibao Nordeste',
    'Cibao Noroeste',
    'Cibao Norte',
    'Cibao Sur',
    'El Valle',
    'Enriquillo',
    'Higuamo',
    'Ozama',
    'Valdesia',
    'Yuma'
  ],
  'EC': [
    'Azuay',
    'Bolívar',
    'Carchi',
    'Cañar',
    'Chimborazo',
    'Cotopaxi',
    'El Oro',
    'Esmeraldas',
    'Galápagos',
    'Guayas',
    'Imbabura',
    'Loja',
    'Los Ríos',
    'Manabí',
    'Morona-Santiago',
    'Napo',
    'Orellana',
    'Pastaza',
    'Pichincha',
    'Santa Elena',
    'Santo Domingo de los Tsáchilas',
    'Sucumbíos',
    'Tungurahua',
    'Zamora-Chinchipe'
  ],
  'EG': [
    'Ad Daqahlīyah',
    'Al Baḩr al Aḩmar',
    'Al Buḩayrah',
    'Al Fayyūm',
    'Al Gharbīyah',
    'Al Iskandarīyah',
    'Al Ismāٰīlīyah',
    'Al Jīzah',
    'Al Minyā',
    'Al Minūfīyah',
    'Al Qalyūbīyah',
    'Al Qāhirah',
    'Al Uqşur',
    'Al Wādī al Jadīd',
    'As Suways',
    'As Sādis min Uktūbar',
    'Ash Sharqīyah',
    'Aswān',
    'Asyūţ',
    'Banī Suwayf',
    'Būr Saٰīd',
    'Dumyāţ',
    'Janūb Sīnā\'',
    'Kafr ash Shaykh',
    'Maţrūḩ',
    'Qinā',
    'Shamāl Sīnā\'',
    'Sūhāj',
    'Ḩulwān'
  ],
  'SV': [
    'Ahuachapán',
    'Cabañas',
    'Chalatenango',
    'Cuscatlán',
    'La Libertad',
    'La Paz',
    'La Unión',
    'Morazán',
    'San Miguel',
    'San Salvador',
    'San Vicente',
    'Santa Ana',
    'Sonsonate',
    'Usulután'
  ],
  'GQ': ['Región Continental', 'Región Insular'],
  'ER': [
    'Al Awsaţ',
    'Al Janūbĩ',
    'Ansabā',
    'Janūbī al Baḩrī al Aḩmar',
    'Qāsh-Barkah',
    'Shimālī al Baḩrī al Aḩmar'
  ],
  'EE': [
    'Harjumaa',
    'Hiiumaa',
    'Ida-Virumaa',
    'Järvamaa',
    'Jõgevamaa',
    'Lääne-Virumaa',
    'Läänemaa',
    'Pärnumaa',
    'Põlvamaa',
    'Raplamaa',
    'Saaremaa',
    'Tartumaa',
    'Valgamaa',
    'Viljandimaa',
    'Võrumaa'
  ],
  'ET': [
    'Bīnshangul Gumuz',
    'Dirē Dawa',
    'Gambēla Hizboch',
    'Hārerī Hizb',
    'Oromīya',
    'Sumalē',
    'Tigray',
    'YeDebub Bihēroch Bihēreseboch na Hizboch',
    'Ādīs Ābeba',
    'Āfar',
    'Āmara'
  ],
  'FJ': ['Central', 'Eastern', 'Northern', 'Rotuma', 'Western'],
  'FI': [
    'Ahvenanmaan maakunta',
    'Etelä-Karjala',
    'Etelä-Pohjanmaa',
    'Etelä-Savo',
    'Kainuu',
    'Kanta-Häme',
    'Keski-Pohjanmaa',
    'Keski-Suomi',
    'Kymenlaakso',
    'Lappi',
    'Pirkanmaa',
    'Pohjanmaa',
    'Pohjois-Karjala',
    'Pohjois-Pohjanmaa',
    'Pohjois-Savo',
    'Päijät-Häme',
    'Satakunta',
    'Uusimaa',
    'Varsinais-Suomi'
  ],
  'FR': [
    'Alsace',
    'Aquitaine',
    'Auvergne',
    'Brittany',
    'Burgundy',
    'Centre-Val de Loire',
    'Champagne-Ardenne',
    'Corsica',
    'Franche-Comté',
    'Languedoc-Roussillon',
    'Limousin',
    'Lorraine',
    'Lower Normandy',
    'Midi-Pyrénées',
    'Nord-Pas-de-Calais',
    'Pays de la Loire',
    'Picardy',
    'Poitou-Charentes',
    'Provence-Alpes-Côte d\'Azur',
    'Rhône-Alpes',
    'Upper Normandy',
    'Île-de-France'
  ],
  'GA': [
    'Estuaire',
    'Haut-Ogooué',
    'Moyen-Ogooué',
    'Ngounié',
    'Nyanga',
    'Ogooué-Ivindo',
    'Ogooué-Lolo',
    'Ogooué-Maritime',
    'Woleu-Ntem'
  ],
  'GM': [
    'Banjul',
    'Central River',
    'Lower River',
    'North Bank',
    'Upper River',
    'Western'
  ],
  'GE': [
    'Abkhazia',
    'Ajaria',
    'Guria',
    'Imereti',
    'K\'akheti',
    'Kvemo Kartli',
    'Mtskheta-Mtianeti',
    'Rach\'a-Lechkhumi-Kvemo Svaneti',
    'Samegrelo-Zemo Svaneti',
    'Samtskhe-Javakheti',
    'Shida Kartli',
    'Tbilisi'
  ],
  'DE': [
    'Baden-Württemberg',
    'Bayern',
    'Berlin',
    'Brandenburg',
    'Bremen',
    'Hamburg',
    'Hessen',
    'Mecklenburg-Vorpommern',
    'Niedersachsen',
    'Nordrhein-Westfalen',
    'Rheinland-Pfalz',
    'Saarland',
    'Sachsen',
    'Sachsen-Anhalt',
    'Schleswig-Holstein',
    'Thüringen'
  ],
  'GH': [
    'Ashanti',
    'Brong-Ahafo',
    'Central',
    'Eastern',
    'Greater Accra',
    'Northern',
    'Upper East',
    'Upper West',
    'Volta',
    'Western'
  ],
  'GR': [
    'Anatoliki Makedonia kai Thraki',
    'Attiki',
    'Dytiki Ellada',
    'Dytiki Makedonia',
    'Ionia Nisia',
    'Ipeiros',
    'Kentriki Makedonia',
    'Kriti',
    'Notio Aigaio',
    'Peloponnisos',
    'Sterea Ellada',
    'Thessalia',
    'Voreio Aigaio'
  ],
  'GL': [
    'Kommune Kujalleq',
    'Kommuneqarfik Sermersooq',
    'Qaasuitsup Kommunia',
    'Qeqqata Kommunia'
  ],
  'GD': [
    'Saint Andrew',
    'Saint David',
    'Saint George',
    'Saint John',
    'Saint Mark',
    'Saint Patrick',
    'Southern Grenadine Islands'
  ],
  'GT': [
    'Alta Verapaz',
    'Baja Verapaz',
    'Chimaltenango',
    'Chiquimula',
    'El Progreso',
    'Escuintla',
    'Guatemala',
    'Huehuetenango',
    'Izabal',
    'Jalapa',
    'Jutiapa',
    'Petén',
    'Quetzaltenango',
    'Quiché',
    'Retalhuleu',
    'Sacatepéquez',
    'San Marcos',
    'Santa Rosa',
    'Sololá',
    'Suchitepéquez',
    'Totonicapán',
    'Zacapa'
  ],
  'GN': [
    'Boké',
    'Conakry',
    'Faranah',
    'Kankan',
    'Kindia',
    'Labé',
    'Mamou',
    'Nzérékoré'
  ],
  'GW': ['Leste', 'Norte', 'Sul'],
  'GY': [
    'Barima-Waini',
    'Cuyuni-Mazaruni',
    'Demerara-Mahaica',
    'East Berbice-Corentyne',
    'Essequibo Islands-West Demerara',
    'Mahaica-Berbice',
    'Pomeroon-Supenaam',
    'Potaro-Siparuni',
    'Upper Demerara-Berbice',
    'Upper Takutu-Upper Essequibo'
  ],
  'HT': [
    'Artibonite',
    'Centre',
    'Grande-Anse',
    'Nippes',
    'Nord',
    'Nord-Est',
    'Nord-Ouest',
    'Ouest',
    'Sud',
    'Sud-Est'
  ],
  'HN': [
    'Atlántida',
    'Choluteca',
    'Colón',
    'Comayagua',
    'Copán',
    'Cortés',
    'El Paraíso',
    'Francisco Morazán',
    'Gracias a Dios',
    'Intibucá',
    'Islas de la Bahía',
    'La Paz',
    'Lempira',
    'Ocotepeque',
    'Olancho',
    'Santa Bárbara',
    'Valle',
    'Yoro'
  ],
  'HU': [
    'Baranya',
    'Borsod-Abaúj-Zemplén',
    'Budapest',
    'Bács-Kiskun',
    'Békés',
    'Békéscsaba',
    'Csongrád',
    'Debrecen',
    'Dunaújváros',
    'Eger',
    'Fejér',
    'Győr',
    'Győr-Moson-Sopron',
    'Hajdú-Bihar',
    'Heves',
    'Hódmezővásárhely',
    'Jász-Nagykun-Szolnok',
    'Kaposvár',
    'Kecskemét',
    'Komárom-Esztergom',
    'Miskolc',
    'Nagykanizsa',
    'Nyíregyháza',
    'Nógrád',
    'Pest',
    'Pécs',
    'Salgótarján',
    'Somogy',
    'Sopron',
    'Szabolcs-Szatmár-Bereg',
    'Szeged',
    'Szekszárd',
    'Szolnok',
    'Szombathely',
    'Székesfehérvár',
    'Tatabánya',
    'Tolna',
    'Vas',
    'Veszprém',
    'Veszprém',
    'Zala',
    'Zalaegerszeg',
    'Érd'
  ],
  'IS': [
    'Austurland',
    'Höfuðborgarsvæði utan Reykjavíkur',
    'Norðurland eystra',
    'Norðurland vestra',
    'Reykjavík',
    'Suðurland',
    'Suðurnes',
    'Vestfirðir',
    'Vesturland'
  ],
  'IN': [
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli',
    'Daman and Diu',
    'Delhi',
    'Lakshadweep',
    'Puducherry',
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu and Kashmir',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal'
  ],
  'ID': [
    'Jawa',
    'Kalimantan',
    'Maluku',
    'Nusa Tenggara',
    'Papua',
    'Sulawesi',
    'Sumatera'
  ],
  'CI': [
    '18 Montagnes',
    'Agnébi',
    'Bafing',
    'Bas-Sassandra',
    'Denguélé',
    'Fromager',
    'Haut-Sassandra',
    'Lacs',
    'Lagunes',
    'Marahoué',
    'Moyen-Cavally',
    'Moyen-Comoé',
    'Nzi-Comoé',
    'Savanes',
    'Sud-Bandama',
    'Sud-Comoé',
    'Vallée du Bandama',
    'Worodougou',
    'Zanzan'
  ],
  'IR': [
    'Alborz',
    'Ardabīl',
    'Būshehr',
    'Chahār Maḩāll va Bakhtīārī',
    'Eşfahān',
    'Fārs',
    'Golestān',
    'Gīlān',
    'Hamadān',
    'Hormozgān',
    'Kermān',
    'Kermānshāh',
    'Khorāsān-e Janūbī',
    'Khorāsān-e Razavī',
    'Khorāsān-e Shemālī',
    'Khūzestān',
    'Kohgīlūyeh va Būyer Aḩmad',
    'Kordestān',
    'Lorestān',
    'Markazī',
    'Māzandarān',
    'Qazvīn',
    'Qom',
    'Semnān',
    'Sīstān va Balūchestān',
    'Tehrān',
    'Yazd',
    'Zanjān',
    'Āz̄arbāyjān-e Gharbī',
    'Āz̄arbāyjān-e Sharqī',
    'Īlām'
  ],
  'IQ': [
    'Al Anbār',
    'Al Başrah',
    'Al Muthanná',
    'Al Qādisīyah',
    'An Najaf',
    'Arbīl',
    'As Sulaymānīyah',
    'At Ta\'mīm',
    'Baghdād',
    'Bābil',
    'Dahūk',
    'Dhī Qār',
    'Diyālá',
    'Karbalā\'',
    'Maysān',
    'Nīnawá',
    'Wāsiţ',
    'Şalāḩ ad Dīn'
  ],
  'IE': ['Connaught', 'Leinster', 'Munster', 'Ulster'],
  'IL': [
    'HaDarom',
    'HaMerkaz',
    'HaTsafon',
    'H̱efa',
    'Tel-Aviv',
    'Yerushalayim'
  ],
  'IT': [
    'Abruzzo',
    'Basilicata',
    'Calabria',
    'Campania',
    'Emilia-Romagna',
    'Friuli-Venezia Giulia',
    'Lazio',
    'Liguria',
    'Lombardia',
    'Marche',
    'Molise',
    'Piemonte',
    'Puglia',
    'Sardegna',
    'Sicilia',
    'Toscana',
    'Trentino-Alto Adige',
    'Umbria',
    'Valle d\'Aosta',
    'Veneto'
  ],
  'JM': [
    'Clarendon',
    'Hanover',
    'Kingston',
    'Manchester',
    'Portland',
    'Saint Andrew',
    'Saint Ann',
    'Saint Catherine',
    'Saint Elizabeth',
    'Saint James',
    'Saint Mary',
    'Saint Thomas',
    'Trelawny',
    'Westmoreland'
  ],
  'JP': [
    'Aiti',
    'Akita',
    'Aomori',
    'Ehime',
    'Gihu',
    'Gunma',
    'Hirosima',
    'Hokkaidô',
    'Hukui',
    'Hukuoka',
    'Hukusima',
    'Hyôgo',
    'Ibaraki',
    'Isikawa',
    'Iwate',
    'Kagawa',
    'Kagosima',
    'Kanagawa',
    'Kumamoto',
    'Kyôto',
    'Kôti',
    'Mie',
    'Miyagi',
    'Miyazaki',
    'Nagano',
    'Nagasaki',
    'Nara',
    'Niigata',
    'Okayama',
    'Okinawa',
    'Saga',
    'Saitama',
    'Siga',
    'Simane',
    'Sizuoka',
    'Tiba',
    'Tokusima',
    'Totigi',
    'Tottori',
    'Toyama',
    'Tôkyô',
    'Wakayama',
    'Yamagata',
    'Yamaguti',
    'Yamanasi',
    'Ôita',
    'Ôsaka'
  ],
  'JO': [
    'Al Balqā\'',
    'Al ʽAqabah',
    'Az Zarqā\'',
    'Aţ Ţafīlah',
    'Irbid',
    'Jerash',
    'Karak',
    'Ma\'ān',
    'Mafraq',
    'Mādabā',
    'ʽAjlūn',
    '‘Ammān'
  ],
  'KZ': [
    'Almaty',
    'Almaty oblysy',
    'Aqmola oblysy',
    'Aqtöbe oblysy',
    'Astana',
    'Atyraū oblysy',
    'Batys Qazaqstan oblysy',
    'Mangghystaū oblysy',
    'Ongtüstik Qazaqstan oblysy',
    'Pavlodar oblysy',
    'Qaraghandy oblysy',
    'Qostanay oblysy',
    'Qyzylorda oblysy',
    'Shyghys Qazaqstan oblysy',
    'Soltüstik Qazaqstan oblysy',
    'Zhambyl oblysy'
  ],
  'KE': [
    'Central',
    'Coast',
    'Eastern',
    'Nairobi',
    'North-Eastern',
    'Nyanza',
    'Rift Valley',
    'Western'
  ],
  'KI': ['Gilbert Islands', 'Line Islands', 'Phoenix Islands'],
  'KW': [
    'Al Aḩmadi',
    'Al Farwānīyah',
    'Al Jahrā’',
    'Al Kuwayt',
    'Mubārak al Kabīr',
    'Ḩawallī'
  ],
  'KG': [
    'Batken',
    'Bishkek',
    'Chü',
    'Jalal-Abad',
    'Naryn',
    'Osh',
    'Talas',
    'Ysyk-Köl'
  ],
  'LA': [
    'Attapu',
    'Bokèo',
    'Bolikhamxai',
    'Champasak',
    'Houaphan',
    'Khammouan',
    'Louang Namtha',
    'Louangphabang',
    'Oudômxai',
    'Phôngsali',
    'Salavan',
    'Savannakhét',
    'Vientiane',
    'Vientiane',
    'Xaignabouli',
    'Xaisômboun',
    'Xiangkhoang',
    'Xékong'
  ],
  'LV': [
    'Aglonas novads',
    'Aizkraukles novads',
    'Aizputes novads',
    'Aknīstes novads',
    'Alojas novads',
    'Alsungas novads',
    'Alūksnes novads',
    'Amatas novads',
    'Apes novads',
    'Auces novads',
    'Babītes novads',
    'Baldones novads',
    'Baltinavas novads',
    'Balvu novads',
    'Bauskas novads',
    'Beverīnas novads',
    'Brocēnu novads',
    'Burtnieku novads',
    'Carnikavas novads',
    'Cesvaines novads',
    'Ciblas novads',
    'Cēsu novads',
    'Dagdas novads',
    'Daugavpils',
    'Daugavpils novads',
    'Dobeles novads',
    'Dundagas novads',
    'Durbes novads',
    'Engures novads',
    'Garkalnes novads',
    'Grobiņas novads',
    'Gulbenes novads',
    'Iecavas novads',
    'Ikšķiles novads',
    'Ilūkstes novads',
    'Inčukalna novads',
    'Jaunjelgavas novads',
    'Jaunpiebalgas novads',
    'Jaunpils novads',
    'Jelgava',
    'Jelgavas novads',
    'Jēkabpils',
    'Jēkabpils novads',
    'Jūrmala',
    'Kandavas novads',
    'Kocēnu novads',
    'Kokneses novads',
    'Krimuldas novads',
    'Krustpils novads',
    'Krāslavas novads',
    'Kuldīgas novads',
    'Kārsavas novads',
    'Lielvārdes novads',
    'Liepāja',
    'Limbažu novads',
    'Lubānas novads',
    'Ludzas novads',
    'Līgatnes novads',
    'Līvānu novads',
    'Madonas novads',
    'Mazsalacas novads',
    'Mālpils novads',
    'Mārupes novads',
    'Mērsraga novads',
    'Naukšēnu novads',
    'Neretas novads',
    'Nīcas novads',
    'Ogres novads',
    'Olaines novads',
    'Ozolnieku novads',
    'Preiļu novads',
    'Priekules novads',
    'Priekuļu novads',
    'Pārgaujas novads',
    'Pāvilostas novads',
    'Pļaviņu novads',
    'Raunas novads',
    'Riebiņu novads',
    'Rojas novads',
    'Ropažu novads',
    'Rucavas novads',
    'Rugāju novads',
    'Rundāles novads',
    'Rēzekne',
    'Rēzeknes novads',
    'Rīga',
    'Rūjienas novads',
    'Salacgrīvas novads',
    'Salas novads',
    'Salaspils novads',
    'Saldus novads',
    'Saulkrastu novads',
    'Siguldas novads',
    'Skrundas novads',
    'Skrīveru novads',
    'Smiltenes novads',
    'Stopiņu novads',
    'Strenču novads',
    'Sējas novads',
    'Talsu novads',
    'Tukuma novads',
    'Tērvetes novads',
    'Vaiņodes novads',
    'Valkas novads',
    'Valmiera',
    'Varakļānu novads',
    'Vecpiebalgas novads',
    'Vecumnieku novads',
    'Ventspils',
    'Ventspils novads',
    'Viesītes novads',
    'Viļakas novads',
    'Viļānu novads',
    'Vārkavas novads',
    'Zilupes novads',
    'Ādažu novads',
    'Ērgļu novads',
    'Ķeguma novads',
    'Ķekavas novads'
  ],
  'LB': [
    'Aakkâr',
    'Baalbek-Hermel',
    'Beyrouth',
    'Béqaa',
    'Liban-Nord',
    'Liban-Sud',
    'Mont-Liban',
    'Nabatîyé'
  ],
  'LS': [
    'Berea',
    'Butha-Buthe',
    'Leribe',
    'Mafeteng',
    'Maseru',
    'Mohale\'s Hoek',
    'Mokhotlong',
    'Qacha\'s Nek',
    'Quthing',
    'Thaba-Tseka'
  ],
  'LR': [
    'Bomi',
    'Bong',
    'Gbarpolu',
    'Grand Bassa',
    'Grand Cape Mount',
    'Grand Gedeh',
    'Grand Kru',
    'Lofa',
    'Margibi',
    'Maryland',
    'Montserrado',
    'Nimba',
    'River Gee',
    'Rivercess',
    'Sinoe'
  ],
  'LY': [
    'Al Buţnān',
    'Al Jabal al Akhḑar',
    'Al Jabal al Gharbī',
    'Al Jifārah',
    'Al Jufrah',
    'Al Kufrah',
    'Al Marj',
    'Al Marqab',
    'Al Wāḩāt',
    'An Nuqaţ al Khams',
    'Az Zāwiyah',
    'Banghāzī',
    'Darnah',
    'Ghāt',
    'Mişrātah',
    'Murzuq',
    'Nālūt',
    'Sabhā',
    'Surt',
    'Wādī al Ḩayāt',
    'Wādī ash Shāţiʾ',
    'Ţarābulus'
  ],
  'LI': [
    'Balzers',
    'Eschen',
    'Gamprin',
    'Mauren',
    'Planken',
    'Ruggell',
    'Schaan',
    'Schellenberg',
    'Triesen',
    'Triesenberg',
    'Vaduz'
  ],
  'LT': [
    'Alytaus Apskritis',
    'Kauno Apskritis',
    'Klaipėdos Apskritis',
    'Marijampolės Apskritis',
    'Panevėžio Apskritis',
    'Tauragės Apskritis',
    'Telšių Apskritis',
    'Utenos Apskritis',
    'Vilniaus Apskritis',
    'Šiaulių Apskritis'
  ],
  'LU': ['Diekirch', 'Grevenmacher', 'Luxembourg'],
  'MK': [
    'Aerodrom',
    'Aračinovo',
    'Berovo',
    'Bitola',
    'Bogdanci',
    'Bogovinje',
    'Bosilovo',
    'Brvenica',
    'Butel',
    'Centar',
    'Centar Župa',
    'Debar',
    'Debarca',
    'Delčevo',
    'Demir Hisar',
    'Demir Kapija',
    'Dojran',
    'Dolneni',
    'Drugovo',
    'Gazi Baba',
    'Gevgelija',
    'Gjorče Petrov',
    'Gostivar',
    'Gradsko',
    'Ilinden',
    'Jegunovce',
    'Karbinci',
    'Karpoš',
    'Kavadarci',
    'Kisela Voda',
    'Kičevo',
    'Konče',
    'Kočani',
    'Kratovo',
    'Kriva Palanka',
    'Krivogaštani',
    'Kruševo',
    'Kumanovo',
    'Lipkovo',
    'Lozovo',
    'Makedonska Kamenica',
    'Makedonski Brod',
    'Mavrovo i Rostuša',
    'Mogila',
    'Negotino',
    'Novaci',
    'Novo Selo',
    'Ohrid',
    'Oslomej',
    'Pehčevo',
    'Petrovec',
    'Plasnica',
    'Prilep',
    'Probištip',
    'Radoviš',
    'Rankovce',
    'Resen',
    'Rosoman',
    'Saraj',
    'Sopište',
    'Staro Nagoričane',
    'Struga',
    'Strumica',
    'Studeničani',
    'Sveti Nikole',
    'Tearce',
    'Tetovo',
    'Valandovo',
    'Vasilevo',
    'Veles',
    'Vevčani',
    'Vinica',
    'Vraneštica',
    'Vrapčište',
    'Zajas',
    'Zelenikovo',
    'Zrnovci',
    'Čair',
    'Čaška',
    'Češinovo-Obleševo',
    'Čučer Sandevo',
    'Štip',
    'Šuto Orizari',
    'Želino'
  ],
  'MG': [
    'Antananarivo',
    'Antsiranana',
    'Fianarantsoa',
    'Mahajanga',
    'Toamasina',
    'Toliara'
  ],
  'MW': ['Central Region', 'Northern Region', 'Southern Region'],
  'MY': [
    'Wilayah Persekutuan Kuala Lumpur',
    'Wilayah Persekutuan Labuan',
    'Wilayah Persekutuan Putrajaya',
    'Johor',
    'Kedah',
    'Kelantan',
    'Melaka',
    'Negeri Sembilan',
    'Pahang',
    'Perak',
    'Perlis',
    'Pulau Pinang',
    'Sabah',
    'Sarawak',
    'Selangor',
    'Terengganu'
  ],
  'MV': [
    'Central',
    'Male',
    'North',
    'North Central',
    'South',
    'South Central',
    'Upper North',
    'Upper South'
  ],
  'ML': [
    'Bamako',
    'Gao',
    'Kayes',
    'Kidal',
    'Koulikoro',
    'Mopti',
    'Sikasso',
    'Ségou',
    'Tombouctou'
  ],
  'MT': [
    'Attard',
    'Balzan',
    'Birgu',
    'Birkirkara',
    'Birżebbuġa',
    'Bormla',
    'Dingli',
    'Fgura',
    'Floriana',
    'Fontana',
    'Gudja',
    'Għajnsielem',
    'Għarb',
    'Għargħur',
    'Għasri',
    'Għaxaq',
    'Gżira',
    'Iklin',
    'Isla',
    'Kalkara',
    'Kerċem',
    'Kirkop',
    'Lija',
    'Luqa',
    'Marsa',
    'Marsaskala',
    'Marsaxlokk',
    'Mdina',
    'Mellieħa',
    'Mosta',
    'Mqabba',
    'Msida',
    'Mtarfa',
    'Munxar',
    'Mġarr',
    'Nadur',
    'Naxxar',
    'Paola',
    'Pembroke',
    'Pietà',
    'Qala',
    'Qormi',
    'Qrendi',
    'Rabat Għawdex',
    'Rabat Malta',
    'Safi',
    'San Lawrenz',
    'San Pawl il-Baħar',
    'San Ġiljan',
    'San Ġwann',
    'Sannat',
    'Santa Luċija',
    'Santa Venera',
    'Siġġiewi',
    'Sliema',
    'Swieqi',
    'Ta\' Xbiex',
    'Tarxien',
    'Valletta',
    'Xagħra',
    'Xewkija',
    'Xgħajra',
    'Ħamrun',
    'Żabbar',
    'Żebbuġ Għawdex',
    'Żebbuġ Malta',
    'Żejtun',
    'Żurrieq'
  ],
  'MH': ['Ralik chain', 'Ratak chain'],
  'MR': [
    'Adrar',
    'Assaba',
    'Brakna',
    'Dakhlet Nouâdhibou',
    'Gorgol',
    'Guidimaka',
    'Hodh ech Chargui',
    'Hodh el Gharbi',
    'Inchiri',
    'Nouakchott',
    'Tagant',
    'Tiris Zemmour',
    'Trarza'
  ],
  'MU': [
    'Agalega Islands',
    'Beau Bassin-Rose Hill',
    'Black River',
    'Cargados Carajos Shoals',
    'Curepipe',
    'Flacq',
    'Grand Port',
    'Moka',
    'Pamplemousses',
    'Plaines Wilhems',
    'Port Louis',
    'Port Louis',
    'Quatre Bornes',
    'Rivière du Rempart',
    'Rodrigues Island',
    'Savanne',
    'Vacoas-Phoenix'
  ],
  'MX': [
    'Distrito Federal',
    'Aguascalientes',
    'Baja California',
    'Baja California Sur',
    'Campeche',
    'Chiapas',
    'Chihuahua',
    'Coahuila',
    'Colima',
    'Durango',
    'Guanajuato',
    'Guerrero',
    'Hidalgo',
    'Jalisco',
    'Michoacán',
    'Morelos',
    'México',
    'Nayarit',
    'Nuevo León',
    'Oaxaca',
    'Puebla',
    'Querétaro',
    'Quintana Roo',
    'San Luis Potosí',
    'Sinaloa',
    'Sonora',
    'Tabasco',
    'Tamaulipas',
    'Tlaxcala',
    'Veracruz',
    'Yucatán',
    'Zacatecas'
  ],
  'FM': ['Chuuk', 'Kosrae', 'Pohnpei', 'Yap'],
  'MD': [
    'Anenii Noi',
    'Basarabeasca',
    'Briceni',
    'Bălţi',
    'Cahul',
    'Cantemir',
    'Chişinău',
    'Cimişlia',
    'Criuleni',
    'Călăraşi',
    'Căuşeni',
    'Donduşeni',
    'Drochia',
    'Dubăsari',
    'Edineţ',
    'Floreşti',
    'Făleşti',
    'Glodeni',
    'Găgăuzia, Unitatea teritorială autonomă',
    'Hînceşti',
    'Ialoveni',
    'Leova',
    'Nisporeni',
    'Ocniţa',
    'Orhei',
    'Rezina',
    'Rîşcani',
    'Soroca',
    'Străşeni',
    'Stînga Nistrului, unitatea teritorială din',
    'Sîngerei',
    'Taraclia',
    'Teleneşti',
    'Tighina',
    'Ungheni',
    'Şoldăneşti',
    'Ştefan Vodă'
  ],
  'MC': [
    'Fontvieille',
    'Jardin Exotique',
    'La Colle',
    'La Condamine',
    'La Gare',
    'La Source',
    'Larvotto',
    'Malbousquet',
    'Monaco-Ville',
    'Moneghetti',
    'Monte-Carlo',
    'Moulins',
    'Port-Hercule',
    'Saint-Roman',
    'Sainte-Dévote',
    'Spélugues',
    'Vallon de la Rousse'
  ],
  'MN': [
    'Arhangay',
    'Bayan-Ölgiy',
    'Bayanhongor',
    'Bulgan',
    'Darhan uul',
    'Dornod',
    'Dornogovĭ',
    'Dundgovĭ',
    'Dzavhan',
    'Govĭ-Altay',
    'Govĭ-Sümber',
    'Hentiy',
    'Hovd',
    'Hövsgöl',
    'Orhon',
    'Selenge',
    'Sühbaatar',
    'Töv',
    'Ulaanbaatar',
    'Uvs',
    'Ömnögovĭ',
    'Övörhangay'
  ],
  'ME': [
    'Andrijevica',
    'Bar',
    'Berane',
    'Bijelo Polje',
    'Budva',
    'Cetinje',
    'Danilovgrad',
    'Gusinje',
    'Herceg-Novi',
    'Kolašin',
    'Kotor',
    'Mojkovac',
    'Nikšić',
    'Petnjica',
    'Plav',
    'Pljevlja',
    'Plužine',
    'Podgorica',
    'Rožaje',
    'Tivat',
    'Ulcinj',
    'Šavnik',
    'Žabljak'
  ],
  'MA': [
    'Chaouia-Ouardigha',
    'Doukhala-Abda',
    'Fès-Boulemane',
    'Gharb-Chrarda-Beni Hssen',
    'Grand Casablanca',
    'Guelmim-Es Smara',
    'L\'Oriental',
    'Laâyoune-Boujdour-Sakia el Hamra',
    'Marrakech-Tensift-Al Haouz',
    'Meknès-Tafilalet',
    'Oued ed Dahab-Lagouira',
    'Rabat-Salé-Zemmour-Zaer',
    'Souss-Massa-Drâa',
    'Tadla-Azilal',
    'Tanger-Tétouan',
    'Taza-Al Hoceima-Taounate'
  ],
  'MZ': [
    'Cabo Delgado',
    'Gaza',
    'Inhambane',
    'Manica',
    'Maputo',
    'Maputo',
    'Nampula',
    'Niassa',
    'Sofala',
    'Tete',
    'Zambézia'
  ],
  'MM': [
    'Ayeyarwady',
    'Bago',
    'Chin',
    'Kachin',
    'Kayah',
    'Kayin',
    'Magway',
    'Mandalay',
    'Mon',
    'Rakhine',
    'Sagaing',
    'Shan',
    'Tanintharyi',
    'Yangon'
  ],
  'NA': [
    'Erongo',
    'Hardap',
    'Karas',
    'Kavango East',
    'Kavango West',
    'Khomas',
    'Kunene',
    'Ohangwena',
    'Omaheke',
    'Omusati',
    'Oshana',
    'Oshikoto',
    'Otjozondjupa',
    'Zambezi'
  ],
  'NR': [
    'Aiwo',
    'Anabar',
    'Anetan',
    'Anibare',
    'Baiti',
    'Boe',
    'Buada',
    'Denigomodu',
    'Ewa',
    'Ijuw',
    'Meneng',
    'Nibok',
    'Uaboe',
    'Yaren'
  ],
  'NP': [
    'Madhya Pashchimanchal',
    'Madhyamanchal',
    'Pashchimanchal',
    'Purwanchal',
    'Sudur Pashchimanchal'
  ],
  'NL': [
    'Drenthe',
    'Flevoland',
    'Fryslân',
    'Gelderland',
    'Groningen',
    'Limburg',
    'Noord-Brabant',
    'Noord-Holland',
    'Overijssel',
    'Utrecht',
    'Zeeland',
    'Zuid-Holland',
    'Aruba',
    'Curaçao',
    'Sint Maarten',
    'Bonaire',
    'Saba',
    'Sint Eustatius'
  ],
  'NZ': [
    'North Island',
    'South Island',
    'Auckland',
    'Bay of Plenty',
    'Canterbury',
    'Hawke\'s Bay',
    'Manawatu-Wanganui',
    'Northland',
    'Otago',
    'Southland',
    'Taranaki',
    'Waikato',
    'Wellington',
    'West Coast',
    'Chatham Islands Territory',
    'Gisborne District',
    'Marlborough District',
    'Nelson City',
    'Tasman District'
  ],
  'NI': [
    'Atlántico Norte',
    'Atlántico Sur',
    'Boaco',
    'Carazo',
    'Chinandega',
    'Chontales',
    'Estelí',
    'Granada',
    'Jinotega',
    'León',
    'Madriz',
    'Managua',
    'Masaya',
    'Matagalpa',
    'Nueva Segovia',
    'Rivas',
    'Río San Juan'
  ],
  'NE': [
    'Agadez',
    'Diffa',
    'Dosso',
    'Maradi',
    'Niamey',
    'Tahoua',
    'Tillabéri',
    'Zinder'
  ],
  'NG': [
    'Abia',
    'Abuja Federal Capital Territory',
    'Adamawa',
    'Akwa Ibom',
    'Anambra',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Enugu',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nassarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara'
  ],
  'KP': [
    'Chagang',
    'Kangwon',
    'North Hamgyong',
    'North Hwanghae',
    'North Pyongan',
    'Pyongyang',
    'Rason',
    'Ryanggang',
    'South Hamgyong',
    'South Hwanghae',
    'South Pyongan'
  ],
  'NO': [
    'Akershus',
    'Aust-Agder',
    'Buskerud',
    'Finnmark',
    'Hedmark',
    'Hordaland',
    'Jan Mayen',
    'Møre og Romsdal',
    'Nord-Trøndelag',
    'Nordland',
    'Oppland',
    'Oslo',
    'Rogaland',
    'Sogn og Fjordane',
    'Svalbard',
    'Sør-Trøndelag',
    'Telemark',
    'Troms',
    'Vest-Agder',
    'Vestfold',
    'Østfold'
  ],
  'OM': [
    'Ad Dākhilīyah',
    'Al Buraymī',
    'Al Bāţinah',
    'Al Wusţá',
    'Ash Sharqīyah',
    'Az̧ Z̧āhirah',
    'Masqaţ',
    'Musandam',
    'Z̧ufār'
  ],
  'PK': [
    'Azad Kashmir',
    'Balochistan',
    'Federally Administered Tribal Areas',
    'Gilgit-Baltistan',
    'Islamabad',
    'Khyber Pakhtunkhwa',
    'Punjab',
    'Sindh'
  ],
  'PW': [
    'Aimeliik',
    'Airai',
    'Angaur',
    'Hatobohei',
    'Kayangel',
    'Koror',
    'Melekeok',
    'Ngaraard',
    'Ngarchelong',
    'Ngardmau',
    'Ngatpang',
    'Ngchesar',
    'Ngeremlengui',
    'Ngiwal',
    'Peleliu',
    'Sonsorol'
  ],
  'PS': [
    'Bethlehem',
    'Deir El Balah',
    'Gaza',
    'Hebron',
    'Jenin',
    'Jericho – Al Aghwar',
    'Jerusalem',
    'Khan Yunis',
    'Nablus',
    'North Gaza',
    'Qalqilya',
    'Rafah',
    'Ramallah',
    'Salfit',
    'Tubas',
    'Tulkarm'
  ],
  'PA': [
    'Bocas del Toro',
    'Chiriquí',
    'Coclé',
    'Colón',
    'Darién',
    'Emberá',
    'Herrera',
    'Kuna Yala',
    'Los Santos',
    'Ngöbe-Buglé',
    'Panamá',
    'Panamá Oeste',
    'Veraguas'
  ],
  'PG': [
    'Bougainville',
    'Central',
    'Chimbu',
    'East New Britain',
    'East Sepik',
    'Eastern Highlands',
    'Enga',
    'Gulf',
    'Madang',
    'Manus',
    'Milne Bay',
    'Morobe',
    'National Capital District',
    'New Ireland',
    'Northern',
    'Sandaun',
    'Southern Highlands',
    'West New Britain',
    'Western',
    'Western Highlands'
  ],
  'PY': [
    'Alto Paraguay',
    'Alto Paraná',
    'Amambay',
    'Asunción',
    'Boquerón',
    'Caaguazú',
    'Caazapá',
    'Canindeyú',
    'Central',
    'Concepción',
    'Cordillera',
    'Guairá',
    'Itapúa',
    'Misiones',
    'Paraguarí',
    'Presidente Hayes',
    'San Pedro',
    'Ñeembucú'
  ],
  'PE': [
    'Amazonas',
    'Ancash',
    'Apurímac',
    'Arequipa',
    'Ayacucho',
    'Cajamarca',
    'Cusco',
    'El Callao',
    'Huancavelica',
    'Huánuco',
    'Ica',
    'Junín',
    'La Libertad',
    'Lambayeque',
    'Lima',
    'Loreto',
    'Madre de Dios',
    'Moquegua',
    'Municipalidad Metropolitana de Lima',
    'Pasco',
    'Piura',
    'Puno',
    'San Martín',
    'Tacna',
    'Tumbes',
    'Ucayali'
  ],
  'PH': [
    'Autonomous Region in Muslim Mindanao',
    'Bicol',
    'Cagayan Valley',
    'Calabarzon',
    'Caraga',
    'Central Luzon',
    'Central Visayas',
    'Cordillera Administrative Region',
    'Davao',
    'Eastern Visayas',
    'Ilocos',
    'Mimaropa',
    'National Capital Region',
    'Northern Mindanao',
    'Soccsksargen',
    'Western Visayas',
    'Zamboanga Peninsula'
  ],
  'PL': [
    'Dolnośląskie',
    'Kujawsko-pomorskie',
    'Lubelskie',
    'Lubuskie',
    'Mazowieckie',
    'Małopolskie',
    'Opolskie',
    'Podkarpackie',
    'Podlaskie',
    'Pomorskie',
    'Warmińsko-mazurskie',
    'Wielkopolskie',
    'Zachodniopomorskie',
    'Łódzkie',
    'Śląskie',
    'Świętokrzyskie'
  ],
  'PT': [
    'Aveiro',
    'Beja',
    'Braga',
    'Bragança',
    'Castelo Branco',
    'Coimbra',
    'Faro',
    'Guarda',
    'Leiria',
    'Lisboa',
    'Portalegre',
    'Porto',
    'Região Autónoma da Madeira',
    'Região Autónoma dos Açores',
    'Santarém',
    'Setúbal',
    'Viana do Castelo',
    'Vila Real',
    'Viseu',
    'Évora'
  ],
  'QA': [
    'Ad Dawḩah',
    'Al Khawr wa adh Dhakhīrah',
    'Al Wakrah',
    'Ar Rayyān',
    'Ash Shamāl',
    'Az̧ Za̧`āyin',
    'Umm Şalāl'
  ],
  'RO': [
    'Alba',
    'Arad',
    'Argeș',
    'Bacău',
    'Bihor',
    'Bistrița-Năsăud',
    'Botoșani',
    'Brașov',
    'Brăila',
    'București',
    'Buzău',
    'Caraș-Severin',
    'Cluj',
    'Constanța',
    'Covasna',
    'Călărași',
    'Dolj',
    'Dâmbovița',
    'Galați',
    'Giurgiu',
    'Gorj',
    'Harghita',
    'Hunedoara',
    'Ialomița',
    'Iași',
    'Ilfov',
    'Maramureș',
    'Mehedinți',
    'Mureș',
    'Neamț',
    'Olt',
    'Prahova',
    'Satu Mare',
    'Sibiu',
    'Suceava',
    'Sălaj',
    'Teleorman',
    'Timiș',
    'Tulcea',
    'Vaslui',
    'Vrancea',
    'Vâlcea'
  ],
  'RU': [
    'Amurskaya oblast\'',
    'Arkhangel\'skaya oblast\'',
    'Astrakhanskaya oblast\'',
    'Belgorodskaya oblast\'',
    'Bryanskaya oblast\'',
    'Chelyabinskaya oblast\'',
    'Irkutskaya oblast\'',
    'Ivanovskaya oblast\'',
    'Kaliningradskaya oblast\'',
    'Kaluzhskaya oblast\'',
    'Kemerovskaya oblast\'',
    'Kirovskaya oblast\'',
    'Kostromskaya oblast\'',
    'Kurganskaya oblast\'',
    'Kurskaya oblast\'',
    'Leningradskaya oblast\'',
    'Lipetskaya oblast\'',
    'Magadanskaya oblast\'',
    'Moskovskaya oblast\'',
    'Murmanskaya oblast\'',
    'Nizhegorodskaya oblast\'',
    'Novgorodskaya oblast\'',
    'Novosibirskaya oblast\'',
    'Omskaya oblast\'',
    'Orenburgskaya oblast\'',
    'Orlovskaya oblast\'',
    'Penzenskaya oblast\'',
    'Pskovskaya oblast\'',
    'Rostovskaya oblast\'',
    'Ryazanskaya oblast\'',
    'Sakhalinskaya oblast\'',
    'Samarskaya oblast\'',
    'Saratovskaya oblast\'',
    'Smolenskaya oblast\'',
    'Sverdlovskaya oblast\'',
    'Tambovskaya oblast\'',
    'Tomskaya oblast\'',
    'Tul\'skaya oblast\'',
    'Tverskaya oblast\'',
    'Tyumenskaya oblast\'',
    'Ul\'yanovskaya oblast\'',
    'Vladimirskaya oblast\'',
    'Volgogradskaya oblast\'',
    'Vologodskaya oblast\'',
    'Voronezhskaya oblast\'',
    'Yaroslavskaya oblast\'',
    'Altayskiy kray',
    'Kamchatskiy kray',
    'Khabarovskiy kray',
    'Krasnodarskiy kray',
    'Krasnoyarskiy kray',
    'Permskiy kray',
    'Primorskiy kray',
    'Stavropol\'skiy kray',
    'Zabaykal\'skiy kray',
    'Moskva',
    'Sankt-Peterburg',
    'Chukotskiy avtonomnyy okrug',
    'Khanty-Mansiyskiy avtonomnyy okrug-Yugra',
    'Nenetskiy avtonomnyy okrug',
    'Yamalo-Nenetskiy avtonomnyy okrug',
    'Yevreyskaya avtonomnaya oblast\'',
    'Adygeya, Respublika',
    'Altay, Respublika',
    'Bashkortostan, Respublika',
    'Buryatiya, Respublika',
    'Chechenskaya Respublika',
    'Chuvashskaya Respublika',
    'Dagestan, Respublika',
    'Ingushetiya, Respublika',
    'Kabardino-Balkarskaya Respublika',
    'Kalmykiya, Respublika',
    'Karachayevo-Cherkesskaya Respublika',
    'Kareliya, Respublika',
    'Khakasiya, Respublika',
    'Komi, Respublika',
    'Mariy El, Respublika',
    'Mordoviya, Respublika',
    'Sakha, Respublika',
    'Severnaya Osetiya-Alaniya, Respublika',
    'Tatarstan, Respublika',
    'Tyva, Respublika',
    'Udmurtskaya Respublika'
  ],
  'RW': ['Est', 'Nord', 'Ouest', 'Sud', 'Ville de Kigali'],
  'SH': ['Ascension', 'Saint Helena', 'Tristan da Cunha'],
  'KN': ['Nevis', 'Saint Kitts'],
  'LC': [
    'Anse la Raye',
    'Castries',
    'Choiseul',
    'Dauphin',
    'Dennery',
    'Gros Islet',
    'Laborie',
    'Micoud',
    'Praslin',
    'Soufrière',
    'Vieux Fort'
  ],
  'VC': [
    'Charlotte',
    'Grenadines',
    'Saint Andrew',
    'Saint David',
    'Saint George',
    'Saint Patrick'
  ],
  'WS': [
    'A\'ana',
    'Aiga-i-le-Tai',
    'Atua',
    'Fa\'asaleleaga',
    'Gaga\'emauga',
    'Gagaifomauga',
    'Palauli',
    'Satupa\'itea',
    'Tuamasaga',
    'Va\'a-o-Fonoti',
    'Vaisigano'
  ],
  'SM': [
    'Acquaviva',
    'Borgo Maggiore',
    'Chiesanuova',
    'Domagnano',
    'Faetano',
    'Fiorentino',
    'Montegiardino',
    'San Marino',
    'Serravalle'
  ],
  'ST': ['Príncipe', 'São Tomé'],
  'SA': [
    'Al Bāḩah',
    'Al Jawf',
    'Al Madīnah',
    'Al Qaşīm',
    'Al Ḩudūd ash Shamālīyah',
    'Ar Riyāḑ',
    'Ash Sharqīyah',
    'Jīzān',
    'Makkah',
    'Najrān',
    'Tabūk',
    'ٰĀsīr',
    'Ḩā\'il'
  ],
  'SN': [
    'Dakar',
    'Diourbel',
    'Fatick',
    'Kaffrine',
    'Kaolack',
    'Kolda',
    'Kédougou',
    'Louga',
    'Matam',
    'Saint-Louis',
    'Sédhiou',
    'Tambacounda',
    'Thiès',
    'Ziguinchor'
  ],
  'RS': ['Kosovo-Metohija', 'Vojvodina'],
  'SC': [
    'Anse Boileau',
    'Anse Etoile',
    'Anse Royale',
    'Anse aux Pins',
    'Au Cap',
    'Baie Lazare',
    'Baie Sainte Anne',
    'Beau Vallon',
    'Bel Air',
    'Bel Ombre',
    'Cascade',
    'English River',
    'Glacis',
    'Grand Anse Mahe',
    'Grand Anse Praslin',
    'La Digue',
    'Les Mamelles',
    'Mont Buxton',
    'Mont Fleuri',
    'Plaisance',
    'Pointe Larue',
    'Port Glaud',
    'Roche Caiman',
    'Saint Louis',
    'Takamaka'
  ],
  'SL': ['Eastern', 'Northern', 'Southern', 'Western Area'],
  'SG': [
    'Central Singapore',
    'North East',
    'North West',
    'South East',
    'South West'
  ],
  'SK': [
    'Banskobystrický kraj',
    'Bratislavský kraj',
    'Košický kraj',
    'Nitriansky kraj',
    'Prešovský kraj',
    'Trenčiansky kraj',
    'Trnavský kraj',
    'Žilinský kraj'
  ],
  'SI': [
    'Ajdovščina',
    'Apače',
    'Beltinci',
    'Benedikt',
    'Bistrica ob Sotli',
    'Bled',
    'Bloke',
    'Bohinj',
    'Borovnica',
    'Bovec',
    'Braslovče',
    'Brda',
    'Brezovica',
    'Brežice',
    'Cankova',
    'Celje',
    'Cerklje na Gorenjskem',
    'Cerknica',
    'Cerkno',
    'Cerkvenjak',
    'Cirkulane',
    'Destrnik',
    'Divača',
    'Dobje',
    'Dobrepolje',
    'Dobrna',
    'Dobrova–Polhov Gradec',
    'Dobrovnik',
    'Dol pri Ljubljani',
    'Dolenjske Toplice',
    'Domžale',
    'Dornava',
    'Dravograd',
    'Duplek',
    'Gorenja vas–Poljane',
    'Gorišnica',
    'Gorje',
    'Gornja Radgona',
    'Gornji Grad',
    'Gornji Petrovci',
    'Grad',
    'Grosuplje',
    'Hajdina',
    'Hodoš',
    'Horjul',
    'Hoče–Slivnica',
    'Hrastnik',
    'Hrpelje-Kozina',
    'Idrija',
    'Ig',
    'Ilirska Bistrica',
    'Ivančna Gorica',
    'Izola',
    'Jesenice',
    'Jezersko',
    'Juršinci',
    'Kamnik',
    'Kanal',
    'Kidričevo',
    'Kobarid',
    'Kobilje',
    'Komen',
    'Komenda',
    'Koper',
    'Kosanjevica na Krki',
    'Kostel',
    'Kozje',
    'Kočevje',
    'Kranj',
    'Kranjska Gora',
    'Križevci',
    'Krško',
    'Kungota',
    'Kuzma',
    'Laško',
    'Lenart',
    'Lendava',
    'Litija',
    'Ljubljana',
    'Ljubno',
    'Ljutomer',
    'Log-Dragomer',
    'Logatec',
    'Lovrenc na Pohorju',
    'Loška Dolina',
    'Loški Potok',
    'Lukovica',
    'Luče',
    'Majšperk',
    'Makole',
    'Maribor',
    'Markovci',
    'Medvode',
    'Mengeš',
    'Metlika',
    'Mežica',
    'Miklavž na Dravskem Polju',
    'Miren–Kostanjevica',
    'Mirna Peč',
    'Mislinja',
    'Mokronog–Trebelno',
    'Moravske Toplice',
    'Moravče',
    'Mozirje',
    'Murska Sobota',
    'Muta',
    'Naklo',
    'Nazarje',
    'Nova Gorica',
    'Novo Mesto',
    'Odranci',
    'Oplotnica',
    'Ormož',
    'Osilnica',
    'Pesnica',
    'Piran',
    'Pivka',
    'Podlehnik',
    'Podvelka',
    'Podčetrtek',
    'Poljčane',
    'Polzela',
    'Postojna',
    'Prebold',
    'Preddvor',
    'Prevalje',
    'Ptuj',
    'Puconci',
    'Radenci',
    'Radeče',
    'Radlje ob Dravi',
    'Radovljica',
    'Ravne na Koroškem',
    'Razkrižje',
    'Rače–Fram',
    'Renče-Vogrsko',
    'Rečica ob Savinji',
    'Ribnica',
    'Ribnica na Pohorju',
    'Rogatec',
    'Rogaška Slatina',
    'Rogašovci',
    'Ruše',
    'Selnica ob Dravi',
    'Semič',
    'Sevnica',
    'Sežana',
    'Slovenj Gradec',
    'Slovenska Bistrica',
    'Slovenske Konjice',
    'Sodražica',
    'Solčava',
    'Središče ob Dravi',
    'Starše',
    'Straža',
    'Sveta Ana',
    'Sveta Trojica v Slovenskih Goricah',
    'Sveti Andraž v Slovenskih Goricah',
    'Sveti Jurij',
    'Sveti Jurij v Slovenskih Goricah',
    'Sveti Tomaž',
    'Tabor',
    'Tišina',
    'Tolmin',
    'Trbovlje',
    'Trebnje',
    'Trnovska Vas',
    'Trzin',
    'Tržič',
    'Turnišče',
    'Velenje',
    'Velika Polana',
    'Velike Lašče',
    'Veržej',
    'Videm',
    'Vipava',
    'Vitanje',
    'Vodice',
    'Vojnik',
    'Vransko',
    'Vrhnika',
    'Vuzenica',
    'Zagorje ob Savi',
    'Zavrč',
    'Zreče',
    'Črenšovci',
    'Črna na Koroškem',
    'Črnomelj',
    'Šalovci',
    'Šempeter–Vrtojba',
    'Šentilj',
    'Šentjernej',
    'Šentjur',
    'Šentrupert',
    'Šenčur',
    'Škocjan',
    'Škofja Loka',
    'Škofljica',
    'Šmarje pri Jelšah',
    'Šmarješke Toplice',
    'Šmartno ob Paki',
    'Šmartno pri Litiji',
    'Šoštanj',
    'Štore',
    'Žalec',
    'Železniki',
    'Žetale',
    'Žiri',
    'Žirovnica',
    'Žužemberk'
  ],
  'SB': [
    'Capital Territory',
    'Central',
    'Choiseul',
    'Guadalcanal',
    'Isabel',
    'Makira-Ulawa',
    'Malaita',
    'Rennell and Bellona',
    'Temotu',
    'Western'
  ],
  'SO': [
    'Awdal',
    'Bakool',
    'Banaadir',
    'Bari',
    'Bay',
    'Galguduud',
    'Gedo',
    'Hiiraan',
    'Jubbada Dhexe',
    'Jubbada Hoose',
    'Mudug',
    'Nugaal',
    'Sanaag',
    'Shabeellaha Dhexe',
    'Shabeellaha Hoose',
    'Sool',
    'Togdheer',
    'Woqooyi Galbeed'
  ],
  'ZA': [
    'Eastern Cape',
    'Free State',
    'Gauteng',
    'KwaZulu-Natal',
    'Limpopo',
    'Mpumalanga',
    'North West',
    'Northern Cape',
    'Western Cape'
  ],
  'KR': [
    'Busan-gwangyeoksi',
    'Chungcheongbuk-do',
    'Chungcheongnam-do',
    'Daegu-gwangyeoksi',
    'Daejeon-gwangyeoksi',
    'Gangwon-do',
    'Gwangju-gwangyeoksi',
    'Gyeonggi-do',
    'Gyeongsangbuk-do',
    'Gyeongsangnam-do',
    'Incheon-gwangyeoksi',
    'Jeju-teukbyeoljachido',
    'Jeollabuk-do',
    'Jeollanam-do',
    'Sejong',
    'Seoul-teukbyeolsi',
    'Ulsan-gwangyeoksi'
  ],
  'SS': [
    'Central Equatoria',
    'Eastern Equatoria',
    'Jonglei',
    'Lakes',
    'Northern Bahr el Ghazal',
    'Unity',
    'Upper Nile',
    'Warrap',
    'Western Bahr el Ghazal',
    'Western Equatoria'
  ],
  'ES': [
    'A Coruña',
    'Albacete',
    'Alicante',
    'Almería',
    'Asturias',
    'Badajoz',
    'Balears',
    'Barcelona',
    'Burgos',
    'Cantabria',
    'Castellón',
    'Ciudad Real',
    'Cuenca',
    'Cáceres',
    'Cádiz',
    'Córdoba',
    'Girona',
    'Granada',
    'Guadalajara',
    'Guipúzcoa',
    'Huelva',
    'Huesca',
    'Jaén',
    'La Rioja',
    'Las Palmas',
    'León',
    'Lleida',
    'Lugo',
    'Madrid',
    'Murcia',
    'Málaga',
    'Navarra',
    'Ourense',
    'Palencia',
    'Pontevedra',
    'Salamanca',
    'Santa Cruz de Tenerife',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Vizcaya',
    'Zamora',
    'Zaragoza',
    'Álava',
    'Ávila',
    'Ceuta',
    'Melilla',
    'Andalucía',
    'Aragón',
    'Asturias, Principado de',
    'Canarias',
    'Cantabria',
    'Castilla y León',
    'Castilla-La Mancha',
    'Catalunya',
    'Extremadura',
    'Galicia',
    'Illes Balears',
    'La Rioja',
    'Madrid, Comunidad de',
    'Murcia, Región de',
    'Navarra, Comunidad Foral de',
    'País Vasco',
    'Valenciana, Comunidad'
  ],
  'LK': [
    'Central Province',
    'Eastern Province',
    'North Central Province',
    'North Western Province',
    'Northern Province',
    'Sabaragamuwa Province',
    'Southern Province',
    'Uva Province',
    'Western Province'
  ],
  'SD': [
    'Al Baḩr al Aḩmar',
    'Al Jazīrah',
    'Al Kharţūm',
    'Al Qaḑārif',
    'An Nīl',
    'An Nīl al Abyaḑ',
    'An Nīl al Azraq',
    'Ash Shamālīyah',
    'Gharb Dārfūr',
    'Janūb Dārfūr',
    'Janūb Kurdufān',
    'Kassalā',
    'Shamāl Dārfūr',
    'Shamāl Kurdufān',
    'Sharq Dārfūr',
    'Sinnār',
    'Zalingei'
  ],
  'SR': [
    'Brokopondo',
    'Commewijne',
    'Coronie',
    'Marowijne',
    'Nickerie',
    'Para',
    'Paramaribo',
    'Saramacca',
    'Sipaliwini',
    'Wanica'
  ],
  'SZ': ['Hhohho', 'Lubombo', 'Manzini', 'Shiselweni'],
  'SE': [
    'Blekinge län',
    'Dalarnas län',
    'Gotlands län',
    'Gävleborgs län',
    'Hallands län',
    'Jämtlands län',
    'Jönköpings län',
    'Kalmar län',
    'Kronobergs län',
    'Norrbottens län',
    'Skåne län',
    'Stockholms län',
    'Södermanlands län',
    'Uppsala län',
    'Värmlands län',
    'Västerbottens län',
    'Västernorrlands län',
    'Västmanlands län',
    'Västra Götalands län',
    'Örebro län',
    'Östergötlands län'
  ],
  'CH': [
    'Aargau',
    'Appenzell Ausserrhoden',
    'Appenzell Innerrhoden',
    'Basel-Landschaft',
    'Basel-Stadt',
    'Bern',
    'Fribourg',
    'Genève',
    'Glarus',
    'Graubünden',
    'Jura',
    'Luzern',
    'Neuchâtel',
    'Nidwalden',
    'Obwalden',
    'Sankt Gallen',
    'Schaffhausen',
    'Schwyz',
    'Solothurn',
    'Thurgau',
    'Ticino',
    'Uri',
    'Valais',
    'Vaud',
    'Zug',
    'Zürich'
  ],
  'SY': [
    'Al Lādhiqīyah',
    'Al Qunayţirah',
    'Al Ḩasakah',
    'Ar Raqqah',
    'As Suwaydā\'',
    'Darٰā',
    'Dayr az Zawr',
    'Dimashq',
    'Idlib',
    'Rīf Dimashq',
    'Ţarţūs',
    'Ḩalab',
    'Ḩamāh',
    'Ḩimş'
  ],
  'TW': [
    'Changhua',
    'Chiayi',
    'Chiayi',
    'Hsinchu',
    'Hsinchu',
    'Hualien',
    'Ilan',
    'Kaohsiung',
    'Kaohsiung',
    'Keelung',
    'Miaoli',
    'Nantou',
    'Penghu',
    'Pingtung',
    'Taichung',
    'Taichung',
    'Tainan',
    'Tainan',
    'Taipei',
    'Taipei',
    'Taitung',
    'Taoyuan',
    'Yunlin'
  ],
  'TJ': ['Dushanbe', 'Khatlon', 'Kŭhistoni Badakhshon', 'Sughd'],
  'TZ': [
    'Arusha',
    'Dar es Salaam',
    'Dodoma',
    'Iringa',
    'Kagera',
    'Kaskazini Pemba',
    'Kaskazini Unguja',
    'Kigoma',
    'Kilimanjaro',
    'Kusini Pemba',
    'Kusini Unguja',
    'Lindi',
    'Manyara',
    'Mara',
    'Mbeya',
    'Mjini Magharibi',
    'Morogoro',
    'Mtwara',
    'Mwanza',
    'Pwani',
    'Rukwa',
    'Ruvuma',
    'Shinyanga',
    'Singida',
    'Tabora',
    'Tanga'
  ],
  'TH': [
    'Amnat Charoen',
    'Ang Thong',
    'Bueng Kan',
    'Buri Ram',
    'Chachoengsao',
    'Chai Nat',
    'Chaiyaphum',
    'Chanthaburi',
    'Chiang Mai',
    'Chiang Rai',
    'Chon Buri',
    'Chumphon',
    'Kalasin',
    'Kamphaeng Phet',
    'Kanchanaburi',
    'Khon Kaen',
    'Krabi',
    'Krung Thep Maha Nakhon',
    'Lampang',
    'Lamphun',
    'Loei',
    'Lop Buri',
    'Mae Hong Son',
    'Maha Sarakham',
    'Mukdahan',
    'Nakhon Nayok',
    'Nakhon Pathom',
    'Nakhon Phanom',
    'Nakhon Ratchasima',
    'Nakhon Sawan',
    'Nakhon Si Thammarat',
    'Nan',
    'Narathiwat',
    'Nong Bua Lam Phu',
    'Nong Khai',
    'Nonthaburi',
    'Pathum Thani',
    'Pattani',
    'Phangnga',
    'Phatthalung',
    'Phatthaya',
    'Phayao',
    'Phetchabun',
    'Phetchaburi',
    'Phichit',
    'Phitsanulok',
    'Phra Nakhon Si Ayutthaya',
    'Phrae',
    'Phuket',
    'Prachin Buri',
    'Prachuap Khiri Khan',
    'Ranong',
    'Ratchaburi',
    'Rayong',
    'Roi Et',
    'Sa Kaeo',
    'Sakon Nakhon',
    'Samut Prakan',
    'Samut Sakhon',
    'Samut Songkhram',
    'Saraburi',
    'Satun',
    'Si Sa Ket',
    'Sing Buri',
    'Songkhla',
    'Sukhothai',
    'Suphan Buri',
    'Surat Thani',
    'Surin',
    'Tak',
    'Trang',
    'Trat',
    'Ubon Ratchathani',
    'Udon Thani',
    'Uthai Thani',
    'Uttaradit',
    'Yala',
    'Yasothon'
  ],
  'TL': [
    'Aileu',
    'Ainaro',
    'Baucau',
    'Bobonaro',
    'Cova Lima',
    'Díli',
    'Ermera',
    'Lautem',
    'Liquiça',
    'Manatuto',
    'Manufahi',
    'Oecussi',
    'Viqueque'
  ],
  'TG': ['Centre', 'Kara', 'Maritime', 'Plateaux', 'Savannes'],
  'TO': ['\'Eua', 'Ha\'apai', 'Niuas', 'Tongatapu', 'Vava\'u'],
  'TT': [
    'Arima',
    'Chaguanas',
    'Couva-Tabaquite-Talparo',
    'Diego Martin',
    'Eastern Tobago',
    'Penal-Debe',
    'Point Fortin',
    'Port of Spain',
    'Princes Town',
    'Rio Claro-Mayaro',
    'San Fernando',
    'San Juan-Laventille',
    'Sangre Grande',
    'Siparia',
    'Tunapuna-Piarco',
    'Western Tobago'
  ],
  'TN': [
    'Ariana',
    'Ben Arous',
    'Bizerte',
    'Béja',
    'Gabès',
    'Gafsa',
    'Jendouba',
    'Kairouan',
    'Kasserine',
    'Kebili',
    'La Manouba',
    'Le Kef',
    'Mahdia',
    'Medenine',
    'Monastir',
    'Nabeul',
    'Sfax',
    'Sidi Bouzid',
    'Siliana',
    'Sousse',
    'Tataouine',
    'Tozeur',
    'Tunis',
    'Zaghouan'
  ],
  'TR': [
    'Adana',
    'Adıyaman',
    'Afyonkarahisar',
    'Aksaray',
    'Amasya',
    'Ankara',
    'Antalya',
    'Ardahan',
    'Artvin',
    'Aydın',
    'Ağrı',
    'Balıkesir',
    'Bartın',
    'Batman',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Denizli',
    'Diyarbakır',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Erzurum',
    'Eskişehir',
    'Gaziantep',
    'Giresun',
    'Gümüşhane',
    'Hakkâri',
    'Hatay',
    'Isparta',
    'Iğdır',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kilis',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Kırklareli',
    'Kırıkkale',
    'Kırşehir',
    'Malatya',
    'Manisa',
    'Mardin',
    'Mersin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Osmaniye',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Tekirdağ',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Uşak',
    'Van',
    'Yalova',
    'Yozgat',
    'Zonguldak',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'İstanbul',
    'İzmir',
    'Şanlıurfa',
    'Şırnak'
  ],
  'TM': ['Ahal', 'Aşgabat', 'Balkan', 'Daşoguz', 'Lebap', 'Mary'],
  'TV': [
    'Funafuti',
    'Nanumanga',
    'Nanumea',
    'Niutao',
    'Nui',
    'Nukufetau',
    'Nukulaelae',
    'Vaitupu'
  ],
  'UG': ['Central', 'Eastern', 'Northern', 'Western'],
  'UA': [
    'Avtonomna Respublika Krym',
    'Cherkas\'ka Oblast\'',
    'Chernihivs\'ka Oblast\'',
    'Chernivets\'ka Oblast\'',
    'Dnipropetrovs\'ka Oblast\'',
    'Donets\'ka Oblast\'',
    'Ivano-Frankivs\'ka Oblast\'',
    'Kharkivs\'ka Oblast\'',
    'Khersons\'ka Oblast\'',
    'Khmel\'nyts\'ka Oblast\'',
    'Kirovohrads\'ka Oblast\'',
    'Kyïv',
    'Kyïvs\'ka Oblast\'',
    'L\'vivs\'ka Oblast\'',
    'Luhans\'ka Oblast\'',
    'Mykolaïvs\'ka Oblast\'',
    'Odes\'ka Oblast\'',
    'Poltavs\'ka Oblast\'',
    'Rivnens\'ka Oblast\'',
    'Sevastopol\'',
    'Sums\'ka Oblast\'',
    'Ternopil\'s\'ka Oblast\'',
    'Vinnyts\'ka Oblast\'',
    'Volyns\'ka Oblast\'',
    'Zakarpats\'ka Oblast\'',
    'Zaporiz\'ka Oblast\'',
    'Zhytomyrs\'ka Oblast\''
  ],
  'AE': [
    '\'Ajmān',
    'Abū Z̧aby',
    'Al Fujayrah',
    'Ash Shāriqah',
    'Dubayy',
    'Ra\'s al Khaymah',
    'Umm al Qaywayn'
  ],
  'GB': [
    'Barking and Dagenham',
    'Barnet',
    'Bexley',
    'Brent',
    'Bromley',
    'Camden',
    'Croydon',
    'Ealing',
    'Enfield',
    'Greenwich',
    'Hackney',
    'Hammersmith and Fulham',
    'Haringey',
    'Harrow',
    'Havering',
    'Hillingdon',
    'Hounslow',
    'Islington',
    'Kensington and Chelsea',
    'Kingston upon Thames',
    'Lambeth',
    'Lewisham',
    'Merton',
    'Newham',
    'Redbridge',
    'Richmond upon Thames',
    'Southwark',
    'Sutton',
    'Tower Hamlets',
    'Waltham Forest',
    'Wandsworth',
    'Westminster',
    'England and Wales',
    'Great Britain',
    'United Kingdom',
    'London, City of',
    'Aberdeen City',
    'Aberdeenshire',
    'Angus',
    'Argyll and Bute',
    'Clackmannanshire',
    'Dumfries and Galloway',
    'Dundee City',
    'East Ayrshire',
    'East Dunbartonshire',
    'East Lothian',
    'East Renfrewshire',
    'Edinburgh, City of',
    'Eilean Siar',
    'Falkirk',
    'Fife',
    'Glasgow City',
    'Highland',
    'Inverclyde',
    'Midlothian',
    'Moray',
    'North Ayrshire',
    'North Lanarkshire',
    'Orkney Islands',
    'Perth and Kinross',
    'Renfrewshire',
    'Scottish Borders, The',
    'Shetland Islands',
    'South Ayrshire',
    'South Lanarkshire',
    'Stirling',
    'West Dunbartonshire',
    'West Lothian',
    'England',
    'Scotland',
    'Wales',
    'Antrim',
    'Ards',
    'Armagh',
    'Ballymena',
    'Ballymoney',
    'Banbridge',
    'Belfast',
    'Carrickfergus',
    'Castlereagh',
    'Coleraine',
    'Cookstown',
    'Craigavon',
    'Derry',
    'Down',
    'Dungannon and South Tyrone',
    'Fermanagh',
    'Larne',
    'Limavady',
    'Lisburn',
    'Magherafelt',
    'Moyle',
    'Newry and Mourne District',
    'Newtownabbey',
    'North Down',
    'Omagh',
    'Strabane',
    'Barnsley',
    'Birmingham',
    'Bolton',
    'Bradford',
    'Bury',
    'Calderdale',
    'Coventry',
    'Doncaster',
    'Dudley',
    'Gateshead',
    'Kirklees',
    'Knowsley',
    'Leeds',
    'Liverpool',
    'Manchester',
    'Newcastle upon Tyne',
    'North Tyneside',
    'Oldham',
    'Rochdale',
    'Rotherham',
    'Salford',
    'Sandwell',
    'Sefton',
    'Sheffield',
    'Solihull',
    'South Tyneside',
    'St. Helens',
    'Stockport',
    'Sunderland',
    'Tameside',
    'Trafford',
    'Wakefield',
    'Walsall',
    'Wigan',
    'Wirral',
    'Wolverhampton',
    'Northern Ireland',
    'Buckinghamshire',
    'Cambridgeshire',
    'Cumbria',
    'Derbyshire',
    'Devon',
    'Dorset',
    'East Sussex',
    'Essex',
    'Gloucestershire',
    'Hampshire',
    'Hertfordshire',
    'Kent',
    'Lancashire',
    'Leicestershire',
    'Lincolnshire',
    'Norfolk',
    'North Yorkshire',
    'Northamptonshire',
    'Nottinghamshire',
    'Oxfordshire',
    'Somerset',
    'Staffordshire',
    'Suffolk',
    'Surrey',
    'Warwickshire',
    'West Sussex',
    'Worcestershire',
    'Bath and North East Somerset',
    'Bedford',
    'Blackburn with Darwen',
    'Blackpool',
    'Blaenau Gwent',
    'Bournemouth',
    'Bracknell Forest',
    'Bridgend',
    'Brighton and Hove',
    'Bristol, City of',
    'Caerphilly',
    'Cardiff',
    'Carmarthenshire',
    'Central Bedfordshire',
    'Ceredigion',
    'Cheshire East',
    'Cheshire West and Chester',
    'Conwy',
    'Cornwall',
    'Darlington',
    'Denbighshire',
    'Derby',
    'Durham, County',
    'East Riding of Yorkshire',
    'Flintshire',
    'Gwynedd',
    'Halton',
    'Hartlepool',
    'Herefordshire',
    'Isle of Anglesey',
    'Isle of Wight',
    'Isles of Scilly',
    'Kingston upon Hull',
    'Leicester',
    'Luton',
    'Medway',
    'Merthyr Tydfil',
    'Middlesbrough',
    'Milton Keynes',
    'Monmouthshire',
    'Neath Port Talbot',
    'Newport',
    'North East Lincolnshire',
    'North Lincolnshire',
    'North Somerset',
    'Northumberland',
    'Nottingham',
    'Pembrokeshire',
    'Peterborough',
    'Plymouth',
    'Poole',
    'Portsmouth',
    'Powys',
    'Reading',
    'Redcar and Cleveland',
    'Rhondda, Cynon, Taff',
    'Rutland',
    'Shropshire',
    'Slough',
    'South Gloucestershire',
    'Southampton',
    'Southend-on-Sea',
    'Stockton-on-Tees',
    'Stoke-on-Trent',
    'Swansea',
    'Swindon',
    'Telford and Wrekin',
    'Thurrock',
    'Torbay',
    'Torfaen',
    'Vale of Glamorgan, The',
    'Warrington',
    'West Berkshire',
    'Wiltshire',
    'Windsor and Maidenhead',
    'Wokingham',
    'Wrexham',
    'York'
  ],
  'US': [
    'District of Columbia',
    'American Samoa',
    'Guam',
    'Northern Mariana Islands',
    'Puerto Rico',
    'United States Minor Outlying Islands',
    'Virgin Islands, U.S.',
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming'
  ],
  'UY': [
    'Artigas',
    'Canelones',
    'Cerro Largo',
    'Colonia',
    'Durazno',
    'Flores',
    'Florida',
    'Lavalleja',
    'Maldonado',
    'Montevideo',
    'Paysandú',
    'Rivera',
    'Rocha',
    'Río Negro',
    'Salto',
    'San José',
    'Soriano',
    'Tacuarembó',
    'Treinta y Tres'
  ],
  'UZ': [
    'Andijon',
    'Buxoro',
    'Farg‘ona',
    'Jizzax',
    'Namangan',
    'Navoiy',
    'Qashqadaryo',
    'Qoraqalpog‘iston Respublikasi',
    'Samarqand',
    'Sirdaryo',
    'Surxondaryo',
    'Toshkent',
    'Toshkent',
    'Xorazm'
  ],
  'VU': ['Malampa', 'Pénama', 'Sanma', 'Shéfa', 'Taféa', 'Torba'],
  'VE': [
    'Amazonas',
    'Anzoátegui',
    'Apure',
    'Aragua',
    'Barinas',
    'Bolívar',
    'Carabobo',
    'Cojedes',
    'Delta Amacuro',
    'Dependencias Federales',
    'Distrito Capital',
    'Falcón',
    'Guárico',
    'Lara',
    'Miranda',
    'Monagas',
    'Mérida',
    'Nueva Esparta',
    'Portuguesa',
    'Sucre',
    'Trujillo',
    'Táchira',
    'Vargas',
    'Yaracuy',
    'Zulia'
  ],
  'VN': [
    'An Giang',
    'Bà Rịa–Vũng Tàu',
    'Bình Dương',
    'Bình Phước',
    'Bình Thuận',
    'Bình Định',
    'Bạc Liêu',
    'Bắc Giang',
    'Bắc Kạn',
    'Bắc Ninh',
    'Bến Tre',
    'Cao Bằng',
    'Cà Mau',
    'Cần Thơ',
    'Gia Lai',
    'Hà Giang',
    'Hà Nam',
    'Hà Nội',
    'Hà Tây',
    'Hà Tĩnh',
    'Hòa Bình',
    'Hưng Yên',
    'Hải Dương',
    'Hải Phòng',
    'Hậu Giang',
    'Hồ Chí Minh',
    'Khánh Hòa',
    'Kiên Giang',
    'Kon Tum',
    'Lai Châu',
    'Long An',
    'Lào Cai',
    'Lâm Đồng',
    'Lạng Sơn',
    'Nam Định',
    'Nghệ An',
    'Ninh Bình',
    'Ninh Thuận',
    'Phú Thọ',
    'Phú Yên',
    'Quảng Bình',
    'Quảng Nam',
    'Quảng Ngãi',
    'Quảng Ninh',
    'Quảng Trị',
    'Sóc Trăng',
    'Sơn La',
    'Thanh Hóa',
    'Thái Bình',
    'Thái Nguyên',
    'Thừa Thiên–Huế',
    'Tiền Giang',
    'Trà Vinh',
    'Tuyên Quang',
    'Tây Ninh',
    'Vĩnh Long',
    'Vĩnh Phúc',
    'Yên Bái',
    'Điện Biên',
    'Đà Nẵng',
    'Đắk Lắk',
    'Đắk Nông',
    'Đồng Nai',
    'Đồng Tháp'
  ],
  'YE': [
    '\'Adan',
    '\'Amrān',
    'Abyān',
    'Al Bayḑā\'',
    'Al Jawf',
    'Al Mahrah',
    'Al Maḩwīt',
    'Al Ḩudaydah',
    'Aḑ Ḑāli\'',
    'Dhamār',
    'Ibb',
    'Laḩij',
    'Ma\'rib',
    'Raymah',
    'Shabwah',
    'Tā‘izz',
    'Şan‘ā\'',
    'Şan‘ā\'',
    'Şā‘dah',
    'Ḩajjah',
    'Ḩaḑramawt'
  ],
  'ZM': [
    'Central',
    'Copperbelt',
    'Eastern',
    'Luapula',
    'Lusaka',
    'North-Western',
    'Northern',
    'Southern',
    'Western'
  ],
  'ZW': [
    'Bulawayo',
    'Harare',
    'Manicaland',
    'Mashonaland Central',
    'Mashonaland East',
    'Mashonaland West',
    'Masvingo',
    'Matabeleland North',
    'Matabeleland South',
    'Midlands'
  ],
};

final List<Map<String,dynamic>> nigeriaLGAS=
[
  {
    "state": "Adamawa",
    "alias": "adamawa",
    "lgas": [
      "Demsa",
      "Fufure",
      "Ganye",
      "Gayuk",
      "Gombi",
      "Grie",
      "Hong",
      "Jada",
      "Larmurde",
      "Madagali",
      "Maiha",
      "Mayo Belwa",
      "Michika",
      "Mubi North",
      "Mubi South",
      "Numan",
      "Shelleng",
      "Song",
      "Toungo",
      "Yola North",
      "Yola South"
    ]
  },
  {
    "state": "Akwa Ibom",
    "alias": "akwa_ibom",
    "lgas": [
      "Abak",
      "Eastern Obolo",
      "Eket",
      "Esit Eket",
      "Essien Udim",
      "Etim Ekpo",
      "Etinan",
      "Ibeno",
      "Ibesikpo Asutan",
      "Ibiono-Ibom",
      "Ikot Abasi",
      "Ika",
      "Ikono",
      "Ikot Ekpene",
      "Ini",
      "Mkpat-Enin",
      "Itu",
      "Mbo",
      "Nsit-Atai",
      "Nsit-Ibom",
      "Nsit-Ubium",
      "Obot Akara",
      "Okobo",
      "Onna",
      "Oron",
      "Udung-Uko",
      "Ukanafun",
      "Oruk Anam",
      "Uruan",
      "Urue-Offong/Oruko",
      "Uyo"
    ]
  },
  {
    "state": "Anambra",
    "alias": "anambra",
    "lgas": [
      "Aguata",
      "Anambra East",
      "Anaocha",
      "Awka North",
      "Anambra West",
      "Awka South",
      "Ayamelum",
      "Dunukofia",
      "Ekwusigo",
      "Idemili North",
      "Idemili South",
      "Ihiala",
      "Njikoka",
      "Nnewi North",
      "Nnewi South",
      "Ogbaru",
      "Onitsha North",
      "Onitsha South",
      "Orumba North",
      "Orumba South",
      "Oyi"
    ]
  },
  {
    "state": "Ogun",
    "alias": "ogun",
    "lgas": [
      "Abeokuta North",
      "Abeokuta South",
      "Ado-Odo/Ota",
      "Egbado North",
      "Ewekoro",
      "Egbado South",
      "Ijebu North",
      "Ijebu East",
      "Ifo",
      "Ijebu Ode",
      "Ijebu North East",
      "Imeko Afon",
      "Ikenne",
      "Ipokia",
      "Odeda",
      "Obafemi Owode",
      "Odogbolu",
      "Remo North",
      "Ogun Waterside",
      "Shagamu"
    ]
  },
  {
    "state": "Ondo",
    "alias": "ondo",
    "lgas": [
      "Akoko North-East",
      "Akoko North-West",
      "Akoko South-West",
      "Akoko South-East",
      "Akure North",
      "Akure South",
      "Ese Odo",
      "Idanre",
      "Ifedore",
      "Ilaje",
      "Irele",
      "Ile Oluji/Okeigbo",
      "Odigbo",
      "Okitipupa",
      "Ondo West",
      "Ose",
      "Ondo East",
      "Owo"
    ]
  },
  {
    "state": "Rivers",
    "alias": "rivers",
    "lgas": [
      "Abua/Odual",
      "Ahoada East",
      "Ahoada West",
      "Andoni",
      "Akuku-Toru",
      "Asari-Toru",
      "Bonny",
      "Degema",
      "Emuoha",
      "Eleme",
      "Ikwerre",
      "Etche",
      "Gokana",
      "Khana",
      "Obio/Akpor",
      "Ogba/Egbema/Ndoni",
      "Ogu/Bolo",
      "Okrika",
      "Omuma",
      "Opobo/Nkoro",
      "Oyigbo",
      "Port Harcourt",
      "Tai"
    ]
  },
  {
    "state": "Bauchi",
    "alias": "bauchi",
    "lgas": [
      "Alkaleri",
      "Bauchi",
      "Bogoro",
      "Damban",
      "Darazo",
      "Dass",
      "Gamawa",
      "Ganjuwa",
      "Giade",
      "Itas/Gadau",
      "Jama'are",
      "Katagum",
      "Kirfi",
      "Misau",
      "Ningi",
      "Shira",
      "Tafawa Balewa",
      "Toro",
      "Warji",
      "Zaki"
    ]
  },
  {
    "state": "Benue",
    "alias": "benue",
    "lgas": [
      "Agatu",
      "Apa",
      "Ado",
      "Buruku",
      "Gboko",
      "Guma",
      "Gwer East",
      "Gwer West",
      "Katsina-Ala",
      "Konshisha",
      "Kwande",
      "Logo",
      "Makurdi",
      "Obi",
      "Ogbadibo",
      "Ohimini",
      "Oju",
      "Okpokwu",
      "Oturkpo",
      "Tarka",
      "Ukum",
      "Ushongo",
      "Vandeikya"
    ]
  },
  {
    "state": "Borno",
    "alias": "borno",
    "lgas": [
      "Abadam",
      "Askira/Uba",
      "Bama",
      "Bayo",
      "Biu",
      "Chibok",
      "Damboa",
      "Dikwa",
      "Guzamala",
      "Gubio",
      "Hawul",
      "Gwoza",
      "Jere",
      "Kaga",
      "Kala/Balge",
      "Konduga",
      "Kukawa",
      "Kwaya Kusar",
      "Mafa",
      "Magumeri",
      "Maiduguri",
      "Mobbar",
      "Marte",
      "Monguno",
      "Ngala",
      "Nganzai",
      "Shani"
    ]
  },
  {
    "state": "Bayelsa",
    "alias": "bayelsa",
    "lgas": [
      "Brass",
      "Ekeremor",
      "Kolokuma/Opokuma",
      "Nembe",
      "Ogbia",
      "Sagbama",
      "Southern Ijaw",
      "Yenagoa"
    ]
  },
  {
    "state": "Cross River",
    "alias": "cross_river",
    "lgas": [
      "Abi",
      "Akamkpa",
      "Akpabuyo",
      "Bakassi",
      "Bekwarra",
      "Biase",
      "Boki",
      "Calabar Municipal",
      "Calabar South",
      "Etung",
      "Ikom",
      "Obanliku",
      "Obubra",
      "Obudu",
      "Odukpani",
      "Ogoja",
      "Yakuur",
      "Yala"
    ]
  },
  {
    "state": "Delta",
    "alias": "delta",
    "lgas": [
      "Aniocha North",
      "Aniocha South",
      "Bomadi",
      "Burutu",
      "Ethiope West",
      "Ethiope East",
      "Ika North East",
      "Ika South",
      "Isoko North",
      "Isoko South",
      "Ndokwa East",
      "Ndokwa West",
      "Okpe",
      "Oshimili North",
      "Oshimili South",
      "Patani",
      "Sapele",
      "Udu",
      "Ughelli North",
      "Ukwuani",
      "Ughelli South",
      "Uvwie",
      "Warri North",
      "Warri South",
      "Warri South West"
    ]
  },
  {
    "state": "Ebonyi",
    "alias": "ebonyi",
    "lgas": [
      "Abakaliki",
      "Afikpo North",
      "Ebonyi",
      "Afikpo South",
      "Ezza North",
      "Ikwo",
      "Ezza South",
      "Ivo",
      "Ishielu",
      "Izzi",
      "Ohaozara",
      "Ohaukwu",
      "Onicha"
    ]
  },
  {
    "state": "Edo",
    "alias": "edo",
    "lgas": [
      "Akoko-Edo",
      "Egor",
      "Esan Central",
      "Esan North-East",
      "Esan South-East",
      "Esan West",
      "Etsako Central",
      "Etsako East",
      "Etsako West",
      "Igueben",
      "Ikpoba Okha",
      "Orhionmwon",
      "Oredo",
      "Ovia North-East",
      "Ovia South-West",
      "Owan East",
      "Owan West",
      "Uhunmwonde"
    ]
  },
  {
    "state": "Ekiti",
    "alias": "ekiti",
    "lgas": [
      "Ado Ekiti",
      "Efon",
      "Ekiti East",
      "Ekiti South-West",
      "Ekiti West",
      "Emure",
      "Gbonyin",
      "Ido Osi",
      "Ijero",
      "Ikere",
      "Ilejemeje",
      "Irepodun/Ifelodun",
      "Ikole",
      "Ise/Orun",
      "Moba",
      "Oye"
    ]
  },
  {
    "state": "Enugu",
    "alias": "enugu",
    "lgas": [
      "Awgu",
      "Aninri",
      "Enugu East",
      "Enugu North",
      "Ezeagu",
      "Enugu South",
      "Igbo Etiti",
      "Igbo Eze North",
      "Igbo Eze South",
      "Isi Uzo",
      "Nkanu East",
      "Nkanu West",
      "Nsukka",
      "Udenu",
      "Oji River",
      "Uzo Uwani",
      "Udi"
    ]
  },
  {
    "state": "Abuja Federal Capital Territory",
    "alias": "abuja",
    "lgas": [
      "Abaji",
      "Bwari",
      "Gwagwalada",
      "Kuje",
      "Kwali",
      "Municipal Area Council"
    ]
  },
  {
    "state": "Gombe",
    "alias": "gombe",
    "lgas": [
      "Akko",
      "Balanga",
      "Billiri",
      "Dukku",
      "Funakaye",
      "Gombe",
      "Kaltungo",
      "Kwami",
      "Nafada",
      "Shongom",
      "Yamaltu/Deba"
    ]
  },
  {
    "state": "Jigawa",
    "alias": "jigawa",
    "lgas": [
      "Auyo",
      "Babura",
      "Buji",
      "Biriniwa",
      "Birnin Kudu",
      "Dutse",
      "Gagarawa",
      "Garki",
      "Gumel",
      "Guri",
      "Gwaram",
      "Gwiwa",
      "Hadejia",
      "Jahun",
      "Kafin Hausa",
      "Kazaure",
      "Kiri Kasama",
      "Kiyawa",
      "Kaugama",
      "Maigatari",
      "Malam Madori",
      "Miga",
      "Sule Tankarkar",
      "Roni",
      "Ringim",
      "Yankwashi",
      "Taura"
    ]
  },
  {
    "state": "Oyo",
    "alias": "oyo",
    "lgas": [
      "Afijio",
      "Akinyele",
      "Atiba",
      "Atisbo",
      "Egbeda",
      "Ibadan North",
      "Ibadan North-East",
      "Ibadan North-West",
      "Ibadan South-East",
      "Ibarapa Central",
      "Ibadan South-West",
      "Ibarapa East",
      "Ido",
      "Ibarapa North",
      "Irepo",
      "Iseyin",
      "Itesiwaju",
      "Iwajowa",
      "Kajola",
      "Lagelu",
      "Ogbomosho North",
      "Ogbomosho South",
      "Ogo Oluwa",
      "Olorunsogo",
      "Oluyole",
      "Ona Ara",
      "Orelope",
      "Ori Ire",
      "Oyo",
      "Oyo East",
      "Saki East",
      "Saki West",
      "Surulere Oyo State"
    ]
  },
  {
    "state": "Imo",
    "alias": "imo",
    "lgas": [
      "Aboh Mbaise",
      "Ahiazu Mbaise",
      "Ehime Mbano",
      "Ezinihitte",
      "Ideato North",
      "Ideato South",
      "Ihitte/Uboma",
      "Ikeduru",
      "Isiala Mbano",
      "Mbaitoli",
      "Isu",
      "Ngor Okpala",
      "Njaba",
      "Nkwerre",
      "Nwangele",
      "Obowo",
      "Oguta",
      "Ohaji/Egbema",
      "Okigwe",
      "Orlu",
      "Orsu",
      "Oru East",
      "Oru West",
      "Owerri Municipal",
      "Owerri North",
      "Unuimo",
      "Owerri West"
    ]
  },
  {
    "state": "Kaduna",
    "alias": "kaduna",
    "lgas": [
      "Birnin Gwari",
      "Chikun",
      "Giwa",
      "Ikara",
      "Igabi",
      "Jaba",
      "Jema'a",
      "Kachia",
      "Kaduna North",
      "Kaduna South",
      "Kagarko",
      "Kajuru",
      "Kaura",
      "Kauru",
      "Kubau",
      "Kudan",
      "Lere",
      "Makarfi",
      "Sabon Gari",
      "Sanga",
      "Soba",
      "Zangon Kataf",
      "Zaria"
    ]
  },
  {
    "state": "Kebbi",
    "alias": "kebbi",
    "lgas": [
      "Aleiro",
      "Argungu",
      "Arewa Dandi",
      "Augie",
      "Bagudo",
      "Birnin Kebbi",
      "Bunza",
      "Dandi",
      "Fakai",
      "Gwandu",
      "Jega",
      "Kalgo",
      "Koko/Besse",
      "Maiyama",
      "Ngaski",
      "Shanga",
      "Suru",
      "Sakaba",
      "Wasagu/Danko",
      "Yauri",
      "Zuru"
    ]
  },
  {
    "state": "Kano",
    "alias": "kano",
    "lgas": [
      "Ajingi",
      "Albasu",
      "Bagwai",
      "Bebeji",
      "Bichi",
      "Bunkure",
      "Dala",
      "Dambatta",
      "Dawakin Kudu",
      "Dawakin Tofa",
      "Doguwa",
      "Fagge",
      "Gabasawa",
      "Garko",
      "Garun Mallam",
      "Gezawa",
      "Gaya",
      "Gwale",
      "Gwarzo",
      "Kabo",
      "Kano Municipal",
      "Karaye",
      "Kibiya",
      "Kiru",
      "Kumbotso",
      "Kunchi",
      "Kura",
      "Madobi",
      "Makoda",
      "Minjibir",
      "Nasarawa",
      "Rano",
      "Rimin Gado",
      "Rogo",
      "Shanono",
      "Takai",
      "Sumaila",
      "Tarauni",
      "Tofa",
      "Tsanyawa",
      "Tudun Wada",
      "Ungogo",
      "Warawa",
      "Wudil"
    ]
  },
  {
    "state": "Kogi",
    "alias": "kogi",
    "lgas": [
      "Ajaokuta",
      "Adavi",
      "Ankpa",
      "Bassa",
      "Dekina",
      "Ibaji",
      "Idah",
      "Igalamela Odolu",
      "Ijumu",
      "Kogi",
      "Kabba/Bunu",
      "Lokoja",
      "Ofu",
      "Mopa Muro",
      "Ogori/Magongo",
      "Okehi",
      "Okene",
      "Olamaboro",
      "Omala",
      "Yagba East",
      "Yagba West"
    ]
  },
  {
    "state": "Osun",
    "alias": "osun",
    "lgas": [
      "Aiyedire",
      "Atakunmosa West",
      "Atakunmosa East",
      "Aiyedaade",
      "Boluwaduro",
      "Boripe",
      "Ife East",
      "Ede South",
      "Ife North",
      "Ede North",
      "Ife South",
      "Ejigbo",
      "Ife Central",
      "Ifedayo",
      "Egbedore",
      "Ila",
      "Ifelodun",
      "Ilesa East",
      "Ilesa West",
      "Irepodun",
      "Irewole",
      "Isokan",
      "Iwo",
      "Obokun",
      "Odo Otin",
      "Ola Oluwa",
      "Olorunda",
      "Oriade",
      "Orolu",
      "Osogbo"
    ]
  },
  {
    "state": "Sokoto",
    "alias": "sokoto",
    "lgas": [
      "Gudu",
      "Gwadabawa",
      "Illela",
      "Isa",
      "Kebbe",
      "Kware",
      "Rabah",
      "Sabon Birni",
      "Shagari",
      "Silame",
      "Sokoto North",
      "Sokoto South",
      "Tambuwal",
      "Tangaza",
      "Tureta",
      "Wamako",
      "Wurno",
      "Yabo",
      "Binji",
      "Bodinga",
      "Dange Shuni",
      "Goronyo",
      "Gada"
    ]
  },
  {
    "state": "Plateau",
    "alias": "plateau",
    "lgas": [
      "Bokkos",
      "Barkin Ladi",
      "Bassa",
      "Jos East",
      "Jos North",
      "Jos South",
      "Kanam",
      "Kanke",
      "Langtang South",
      "Langtang North",
      "Mangu",
      "Mikang",
      "Pankshin",
      "Qua'an Pan",
      "Riyom",
      "Shendam",
      "Wase"
    ]
  },
  {
    "state": "Taraba",
    "alias": "taraba",
    "lgas": [
      "Ardo Kola",
      "Bali",
      "Donga",
      "Gashaka",
      "Gassol",
      "Ibi",
      "Jalingo",
      "Karim Lamido",
      "Kumi",
      "Lau",
      "Sardauna",
      "Takum",
      "Ussa",
      "Wukari",
      "Yorro",
      "Zing"
    ]
  },
  {
    "state": "Yobe",
    "alias": "yobe",
    "lgas": [
      "Bade",
      "Bursari",
      "Damaturu",
      "Fika",
      "Fune",
      "Geidam",
      "Gujba",
      "Gulani",
      "Jakusko",
      "Karasuwa",
      "Machina",
      "Nangere",
      "Nguru",
      "Potiskum",
      "Tarmuwa",
      "Yunusari",
      "Yusufari"
    ]
  },
  {
    "state": "Zamfara",
    "alias": "zamfara",
    "lgas": [
      "Anka",
      "Birnin Magaji/Kiyaw",
      "Bakura",
      "Bukkuyum",
      "Bungudu",
      "Gummi",
      "Gusau",
      "Kaura Namoda",
      "Maradun",
      "Shinkafi",
      "Maru",
      "Talata Mafara",
      "Tsafe",
      "Zurmi"
    ]
  },
  {
    "state": "Lagos",
    "alias": "lagos",
    "lgas": [
      "Agege",
      "Ajeromi-Ifelodun",
      "Alimosho",
      "Amuwo-Odofin",
      "Badagry",
      "Apapa",
      "Epe",
      "Eti Osa",
      "Ibeju-Lekki",
      "Ifako-Ijaiye",
      "Ikeja",
      "Ikorodu",
      "Kosofe",
      "Lagos Island",
      "Mushin",
      "Lagos Mainland",
      "Ojo",
      "Oshodi-Isolo",
      "Shomolu",
      "Surulere Lagos State"
    ]
  },
  {
    "state": "Katsina",
    "alias": "katsina",
    "lgas": [
      "Bakori",
      "Batagarawa",
      "Batsari",
      "Baure",
      "Bindawa",
      "Charanchi",
      "Danja",
      "Dandume",
      "Dan Musa",
      "Daura",
      "Dutsi",
      "Dutsin Ma",
      "Faskari",
      "Funtua",
      "Ingawa",
      "Jibia",
      "Kafur",
      "Kaita",
      "Kankara",
      "Kankia",
      "Katsina",
      "Kurfi",
      "Kusada",
      "Mai'Adua",
      "Malumfashi",
      "Mani",
      "Mashi",
      "Matazu",
      "Musawa",
      "Rimi",
      "Sabuwa",
      "Safana",
      "Sandamu",
      "Zango"
    ]
  },
  {
    "state": "Kwara",
    "alias": "kwara",
    "lgas": [
      "Asa",
      "Baruten",
      "Edu",
      "Ilorin East",
      "Ifelodun",
      "Ilorin South",
      "Ekiti Kwara State",
      "Ilorin West",
      "Irepodun",
      "Isin",
      "Kaiama",
      "Moro",
      "Offa",
      "Oke Ero",
      "Oyun",
      "Pategi"
    ]
  },
  {
    "state": "Nasarawa",
    "alias": "nasarawa",
    "lgas": [
      "Akwanga",
      "Awe",
      "Doma",
      "Karu",
      "Keana",
      "Keffi",
      "Lafia",
      "Kokona",
      "Nasarawa Egon",
      "Nasarawa",
      "Obi",
      "Toto",
      "Wamba"
    ]
  },
  {
    "state": "Niger",
    "alias": "niger",
    "lgas": [
      "Agaie",
      "Agwara",
      "Bida",
      "Borgu",
      "Bosso",
      "Chanchaga",
      "Edati",
      "Gbako",
      "Gurara",
      "Katcha",
      "Kontagora",
      "Lapai",
      "Lavun",
      "Mariga",
      "Magama",
      "Mokwa",
      "Mashegu",
      "Moya",
      "Paikoro",
      "Rafi",
      "Rijau",
      "Shiroro",
      "Suleja",
      "Tafa",
      "Wushishi"
    ]
  },
  {
    "state": "Abia",
    "alias": "abia",
    "lgas": [
      "Aba North",
      "Arochukwu",
      "Aba South",
      "Bende",
      "Isiala Ngwa North",
      "Ikwuano",
      "Isiala Ngwa South",
      "Isuikwuato",
      "Obi Ngwa",
      "Ohafia",
      "Osisioma",
      "Ugwunagbo",
      "Ukwa East",
      "Ukwa West",
      "Umuahia North",
      "Umuahia South",
      "Umu Nneochi"
    ]
  }
];