// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHWBifhLadjk61OP_wPkO7msJlpVh9R2I',
    appId: '1:903873599373:android:bacafa624c69d5e9ec4fc4',
    messagingSenderId: '903873599373',
    projectId: 'detty-915f8',
    storageBucket: 'detty-915f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXXEcQNPLjIQK0MrX90vPvUYLe2yqtwg',
    appId: '1:903873599373:ios:8c731fe7c3b8034fec4fc4',
    messagingSenderId: '903873599373',
    projectId: 'detty-915f8',
    storageBucket: 'detty-915f8.firebasestorage.app',
    iosClientId: '903873599373-hnq1ic79ui6lpk32vfab0udsv6bdl27f.apps.googleusercontent.com',
    iosBundleId: 'com.schull.detty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXXEcQNPLjIQK0MrX90vPvUYLe2yqtwg',
    appId: '1:903873599373:ios:8c731fe7c3b8034fec4fc4',
    messagingSenderId: '903873599373',
    projectId: 'detty-915f8',
    storageBucket: 'detty-915f8.firebasestorage.app',
    iosClientId: '903873599373-hnq1ic79ui6lpk32vfab0udsv6bdl27f.apps.googleusercontent.com',
    iosBundleId: 'com.schull.detty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCadQywwOO8peegBLDCe4cKZk1CTcHeHXI',
    appId: '1:903873599373:web:7f0011c129b2b456ec4fc4',
    messagingSenderId: '903873599373',
    projectId: 'detty-915f8',
    authDomain: 'detty-915f8.firebaseapp.com',
    storageBucket: 'detty-915f8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCadQywwOO8peegBLDCe4cKZk1CTcHeHXI',
    appId: '1:903873599373:web:7f0011c129b2b456ec4fc4',
    messagingSenderId: '903873599373',
    projectId: 'detty-915f8',
    authDomain: 'detty-915f8.firebaseapp.com',
    storageBucket: 'detty-915f8.firebasestorage.app',
  );

}